// Test fixtures for the training room's pure modules: the 15 live archetypes
// as they stood on 2026-09-25 (names, colour, style, grapes, sat ranges and
// the nose/palate aroma links with their wset_aroma_terms group_name — read
// read-only from production; the sat data is the seed migrations'
// 20260829222000/…225000 values, the palate lists 20260829228000's), plus two
// synthetic rows the spec's tests call for (§10): a white with no tannin range
// and no aromas, and a Vintage Port (data/training/archetypes-batch-1.json's
// entry). Country/region/appellation names follow spec §4.1's back-fill table.
// Ids are readable stand-ins, not live uuids; a term id is "{group}/{term}".
//
// Signatures: the live rows carry none yet (the column is new, default false).
// Three are flagged HERE ONLY so the bonus has something to hit — Alsace
// Riesling's petrol, Sancerre's gooseberry, Margaux's cedar.
//
// Not a test file (vitest includes *.test.ts only), so it runs nothing itself.
import type { WineColour, WineStyle } from "../../wset/types";
import type { AromaLexicon, Range, TrainingCandidate } from "../types";

/** "{group}/{term}" — the fixture term id. */
export const tid = (group: string, term: string) => `${group}/${term}`;

type Seed = {
  key: string;
  name: string;
  colour: WineColour;
  style: WineStyle;
  country: string;
  region: string;
  appellation: string;
  regional: boolean;
  grapes: [string, string | null];
  sat: Record<string, Range>;
  nose: [string, string][]; // [term, group]
  palate: [string, string][];
  signatures?: string[]; // terms flagged signature (both kinds)
};

const SEEDS: Seed[] = [
  {
    key: "vosne",
    name: "A typical Vosne-Romanée",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Vosne-Romanée AOC",
    regional: false,
    grapes: ["Pinot Noir", null],
    sat: {
      appearanceIntensity: ["MEDIUM", "MEDIUM"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM_PLUS", "HIGH"],
      tannin: ["MEDIUM", "MEDIUM_PLUS"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM", "MEDIUM_PLUS"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["LONG", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["rose", "Floral"], ["violet", "Floral"], ["raspberry", "Red fruit"], ["strawberry", "Red fruit"], ["red cherry", "Red fruit"], ["forest floor", "Red wine"]],
    palate: [["red cherry", "Red fruit"], ["red plum", "Red fruit"], ["earth", "Red wine"], ["mushroom", "Red wine"], ["forest floor", "Red wine"], ["savoury", "Red wine"]],
  },
  {
    key: "chablis",
    name: "A typical Chablis",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Chablis AOC",
    regional: false,
    grapes: ["Chardonnay", null],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON_GREEN", "LEMON"],
      noseIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      development: ["YOUTHFUL", "YOUTHFUL"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM_PLUS", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_MINUS", "MEDIUM"],
      flavourIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      finish: ["MEDIUM_PLUS", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["grapefruit", "Citrus fruit"], ["lemon", "Citrus fruit"], ["wet stones", "Other"], ["biscuit", "Yeast"]],
    palate: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["lime", "Citrus fruit"], ["wet stones", "Other"], ["flint", "Other"]],
  },
  {
    key: "sancerre",
    name: "A typical Sancerre",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Loire",
    appellation: "Sancerre AOC",
    regional: false,
    grapes: ["Sauvignon Blanc", null],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON_GREEN", "LEMON"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "YOUTHFUL"],
      sweetness: ["DRY", "DRY"],
      acidity: ["HIGH", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_MINUS", "MEDIUM"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["MEDIUM", "MEDIUM_PLUS"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["gooseberry", "Green fruit"], ["grapefruit", "Citrus fruit"], ["lime", "Citrus fruit"], ["grass", "Herbaceous"], ["blackcurrant leaf", "Herbaceous"], ["wet stones", "Other"]],
    palate: [["gooseberry", "Green fruit"], ["grapefruit", "Citrus fruit"], ["lime", "Citrus fruit"], ["wet stones", "Other"], ["flint", "Other"]],
    signatures: ["gooseberry"],
  },
  {
    key: "cdp",
    name: "A typical Châteauneuf-du-Pape",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Rhône",
    appellation: "Châteauneuf-du-Pape AOC",
    regional: false,
    grapes: ["Grenache", "Syrah"],
    sat: {
      appearanceIntensity: ["MEDIUM", "DEEP"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["DEVELOPING", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM_MINUS", "MEDIUM"],
      tannin: ["MEDIUM", "MEDIUM_PLUS"],
      alcohol: ["MEDIUM", "HIGH"],
      body: ["MEDIUM_PLUS", "FULL"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["MEDIUM_PLUS", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["blackberry", "Black fruit"], ["black cherry", "Black fruit"], ["black plum", "Black fruit"], ["dried herbs", "Herbal"], ["black pepper", "Spice"], ["liquorice", "Spice"]],
    palate: [["black cherry", "Black fruit"], ["black plum", "Black fruit"], ["dried herbs", "Herbal"], ["liquorice", "Spice"], ["leather", "Red wine"], ["tar", "Red wine"]],
  },
  {
    key: "cote-rotie",
    name: "A typical Côte-Rôtie",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Rhône",
    appellation: "Côte-Rôtie AOC",
    regional: false,
    grapes: ["Syrah", null],
    sat: {
      appearanceIntensity: ["MEDIUM", "DEEP"],
      colourHue: ["PURPLE", "RUBY"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["MEDIUM_PLUS", "HIGH"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_PLUS", "FULL"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["LONG", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["violet", "Floral"], ["blackberry", "Black fruit"], ["black pepper", "Spice"], ["smoke", "Oak"], ["leather", "Red wine"]],
    palate: [["blackberry", "Black fruit"], ["black pepper", "Spice"], ["smoke", "Oak"], ["leather", "Red wine"], ["game", "Red wine"]],
  },
  {
    key: "margaux",
    name: "A typical Margaux",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Bordeaux",
    appellation: "Margaux AOC",
    regional: false,
    grapes: ["Cabernet Sauvignon", "Merlot"],
    sat: {
      appearanceIntensity: ["MEDIUM", "DEEP"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["MEDIUM_PLUS", "HIGH"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_PLUS", "FULL"],
      flavourIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      finish: ["LONG", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["blackcurrant", "Black fruit"], ["black cherry", "Black fruit"], ["mint", "Herbal"], ["vanilla", "Oak"], ["cedar", "Oak"], ["tobacco", "Red wine"]],
    palate: [["blackcurrant", "Black fruit"], ["black cherry", "Black fruit"], ["cedar", "Oak"], ["leather", "Red wine"], ["tobacco", "Red wine"]],
    signatures: ["cedar"],
  },
  {
    key: "sauternes",
    name: "A typical Sauternes",
    colour: "WHITE",
    style: "SWEET",
    country: "France",
    region: "Bordeaux",
    appellation: "Sauternes AOC",
    regional: false,
    grapes: ["Semillon", "Sauvignon Blanc"],
    sat: {
      appearanceIntensity: ["MEDIUM", "DEEP"],
      colourHue: ["GOLD", "AMBER"],
      noseIntensity: ["PRONOUNCED", "PRONOUNCED"],
      development: ["DEVELOPING", "FULLY_DEVELOPED"],
      sweetness: ["SWEET", "LUSCIOUS"],
      acidity: ["MEDIUM_PLUS", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "HIGH"],
      body: ["FULL", "FULL"],
      flavourIntensity: ["PRONOUNCED", "PRONOUNCED"],
      finish: ["LONG", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apricot", "Stone fruit"], ["vanilla", "Oak"], ["orange marmalade", "White wine"], ["ginger", "White wine"], ["honey", "White wine"]],
    palate: [["caramel", "Red wine"], ["dried apricot", "White wine"], ["orange marmalade", "White wine"], ["ginger", "White wine"], ["honey", "White wine"]],
  },
  {
    key: "champagne",
    name: "A typical Champagne",
    colour: "WHITE",
    style: "SPARKLING",
    country: "France",
    region: "Champagne",
    appellation: "Champagne AOC",
    regional: true,
    grapes: ["Chardonnay", "Pinot Noir"],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON_GREEN", "GOLD"],
      noseIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "OFF_DRY"],
      acidity: ["HIGH", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_MINUS", "MEDIUM"],
      flavourIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      finish: ["MEDIUM_PLUS", "LONG"],
      mousse: ["CREAMY", "CREAMY"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["biscuit", "Yeast"], ["bread", "Yeast"], ["brioche", "Yeast"]],
    palate: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["toast", "Yeast"], ["brioche", "Yeast"], ["cream", "Malolactic"], ["hazelnut", "White wine"]],
  },
  {
    key: "alsace-riesling",
    name: "A typical Alsace Riesling",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Alsace",
    appellation: "Alsace AOC",
    regional: true,
    grapes: ["Riesling", null],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON_GREEN", "LEMON"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "OFF_DRY"],
      acidity: ["HIGH", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_MINUS", "MEDIUM"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["MEDIUM_PLUS", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["lime", "Citrus fruit"], ["apricot", "Stone fruit"], ["petrol", "White wine"], ["honey", "White wine"]],
    palate: [["apple", "Green fruit"], ["lime", "Citrus fruit"], ["peach", "Stone fruit"], ["wet stones", "Other"], ["petrol", "White wine"]],
    signatures: ["petrol"],
  },
  {
    key: "bandol",
    name: "A typical Bandol",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Provence",
    appellation: "Bandol AOC",
    regional: false,
    grapes: ["Mourvèdre", null],
    sat: {
      appearanceIntensity: ["DEEP", "DEEP"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["HIGH", "HIGH"],
      alcohol: ["MEDIUM", "HIGH"],
      body: ["FULL", "FULL"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["LONG", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["blackberry", "Black fruit"], ["black cherry", "Black fruit"], ["dried herbs", "Herbal"], ["black pepper", "Spice"], ["liquorice", "Spice"], ["leather", "Red wine"]],
    palate: [["blackberry", "Black fruit"], ["black cherry", "Black fruit"], ["liquorice", "Spice"], ["leather", "Red wine"], ["game", "Red wine"], ["tar", "Red wine"]],
  },
  {
    key: "petit-chablis",
    name: "A typical Petit Chablis",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Petit Chablis AOC",
    regional: false,
    grapes: ["Chardonnay", null],
    sat: {
      appearanceIntensity: ["PALE", "PALE"],
      colourHue: ["LEMON_GREEN", "LEMON"],
      noseIntensity: ["MEDIUM_MINUS", "MEDIUM"],
      development: ["YOUTHFUL", "YOUTHFUL"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM_PLUS", "HIGH"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["LIGHT", "MEDIUM_MINUS"],
      flavourIntensity: ["MEDIUM_MINUS", "MEDIUM"],
      finish: ["MEDIUM_MINUS", "MEDIUM"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["grapefruit", "Citrus fruit"], ["lemon", "Citrus fruit"], ["wet stones", "Other"]],
    palate: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["lime", "Citrus fruit"], ["wet stones", "Other"]],
  },
  {
    key: "cote-de-nuits",
    name: "A typical Côte de Nuits",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Bourgogne AOC",
    regional: true,
    grapes: ["Pinot Noir", null],
    sat: {
      appearanceIntensity: ["MEDIUM", "MEDIUM"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM_PLUS", "HIGH"],
      tannin: ["MEDIUM", "MEDIUM_PLUS"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM", "MEDIUM_PLUS"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["MEDIUM_PLUS", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["violet", "Floral"], ["raspberry", "Red fruit"], ["red cherry", "Red fruit"], ["black cherry", "Black fruit"], ["forest floor", "Red wine"]],
    palate: [["red cherry", "Red fruit"], ["black cherry", "Black fruit"], ["earth", "Red wine"], ["mushroom", "Red wine"], ["forest floor", "Red wine"], ["savoury", "Red wine"]],
  },
  {
    key: "cote-de-beaune",
    name: "A typical Côte de Beaune",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Bourgogne AOC",
    regional: true,
    grapes: ["Chardonnay", null],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON", "GOLD"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM", "MEDIUM_PLUS"],
      flavourIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      finish: ["MEDIUM_PLUS", "LONG"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["biscuit", "Yeast"], ["vanilla", "Oak"], ["honey", "White wine"]],
    palate: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["toast", "Yeast"], ["butter", "Malolactic"], ["vanilla", "Oak"], ["hazelnut", "White wine"]],
  },
  {
    key: "maconnais",
    name: "A typical Mâconnais",
    colour: "WHITE",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Macon AOC",
    regional: false,
    grapes: ["Chardonnay", null],
    sat: {
      appearanceIntensity: ["PALE", "MEDIUM"],
      colourHue: ["LEMON", "GOLD"],
      noseIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      development: ["YOUTHFUL", "YOUTHFUL"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["LOW", "LOW"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM_MINUS", "MEDIUM"],
      flavourIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      finish: ["MEDIUM", "MEDIUM_PLUS"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["apricot", "Stone fruit"], ["honey", "White wine"]],
    palate: [["apple", "Green fruit"], ["lemon", "Citrus fruit"], ["peach", "Stone fruit"], ["melon", "Tropical fruit"], ["hazelnut", "White wine"]],
  },
  {
    key: "cote-chalonnaise",
    name: "A typical Côte Chalonnaise",
    colour: "RED",
    style: "STILL",
    country: "France",
    region: "Bourgogne",
    appellation: "Cote Chalonnaise AOC",
    regional: false,
    grapes: ["Pinot Noir", null],
    sat: {
      appearanceIntensity: ["MEDIUM", "MEDIUM"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      development: ["YOUTHFUL", "DEVELOPING"],
      sweetness: ["DRY", "DRY"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["MEDIUM", "MEDIUM"],
      alcohol: ["MEDIUM", "MEDIUM"],
      body: ["MEDIUM", "MEDIUM"],
      flavourIntensity: ["MEDIUM", "MEDIUM_PLUS"],
      finish: ["MEDIUM", "MEDIUM_PLUS"],
      clarity: ["CLEAR", "CLEAR"],
    },
    nose: [["raspberry", "Red fruit"], ["strawberry", "Red fruit"], ["red cherry", "Red fruit"], ["dried herbs", "Herbal"]],
    palate: [["strawberry", "Red fruit"], ["red cherry", "Red fruit"], ["red plum", "Red fruit"], ["earth", "Red wine"], ["savoury", "Red wine"]],
  },
  // --- synthetic (spec §10) ---------------------------------------------------
  {
    key: "tannin-free-white",
    name: "A typical Tannin-free White",
    colour: "WHITE",
    style: "STILL",
    country: "Austria",
    region: "Niederösterreich",
    appellation: "Niederösterreich",
    regional: true,
    grapes: ["Grüner Veltliner", null],
    sat: {
      sweetness: ["DRY", "DRY"],
      acidity: ["HIGH", "HIGH"],
      body: ["MEDIUM", "MEDIUM"],
    },
    nose: [],
    palate: [],
  },
  {
    key: "vintage-port",
    name: "A typical Vintage Port",
    colour: "RED",
    style: "FORTIFIED",
    country: "Portugal",
    region: "Porto",
    appellation: "Porto DOC",
    regional: false,
    grapes: ["Touriga Nacional", "Touriga Franca"],
    sat: {
      appearanceIntensity: ["DEEP", "DEEP"],
      colourHue: ["RUBY", "GARNET"],
      noseIntensity: ["MEDIUM_PLUS", "PRONOUNCED"],
      development: ["DEVELOPING", "FULLY_DEVELOPED"],
      sweetness: ["MEDIUM_SWEET", "SWEET"],
      acidity: ["MEDIUM", "MEDIUM_PLUS"],
      tannin: ["MEDIUM_PLUS", "HIGH"],
      // FORTIFIED_ALCOHOL_STOPS, for the reference sheet only (D19)
      alcohol: ["MEDIUM_PLUS", "HIGH"],
      body: ["FULL", "FULL"],
      flavourIntensity: ["PRONOUNCED", "PRONOUNCED"],
      finish: ["LONG", "LONG"],
    },
    nose: [["blackberry", "Black fruit"], ["black plum", "Black fruit"], ["violet", "Floral"], ["liquorice", "Spice"], ["cooked blackberry", "Red wine"]],
    palate: [["blackberry", "Black fruit"], ["black plum", "Black fruit"], ["prune", "Red wine"], ["liquorice", "Spice"], ["chocolate", "Oak"]],
  },
];

function toCandidate(s: Seed): TrainingCandidate {
  const sig = new Set(s.signatures ?? []);
  const link = (kind: "NOSE" | "PALATE") => ([term, group]: [string, string]) => ({
    termId: tid(group, term),
    term,
    group,
    kind,
    signature: sig.has(term),
  });
  return {
    id: `arch-${s.key}`,
    name: s.name,
    description: null,
    colour: s.colour,
    style: s.style,
    country: { id: `country-${s.country}`, name: s.country },
    region: { id: `region-${s.region}`, name: s.region },
    appellation: { id: `app-${s.appellation}`, name: s.appellation, isRegional: s.regional },
    primaryGrape: { id: `grape-${s.grapes[0]}`, name: s.grapes[0] },
    secondaryGrape: s.grapes[1] ? { id: `grape-${s.grapes[1]}`, name: s.grapes[1] } : null,
    designations: [],
    typicalAge: null,
    sat: s.sat,
    aromas: [...s.nose.map(link("NOSE")), ...s.palate.map(link("PALATE"))],
    placeCanonicalKey: null,
    qualityLow: null,
    qualityHigh: null,
  };
}

/** Every fixture candidate: the 15 live archetypes, then the two synthetic. */
export const POOL: TrainingCandidate[] = SEEDS.map(toCandidate);

/** One fixture by its key ("margaux", "vintage-port", …). */
export function arch(key: string): TrainingCandidate {
  const c = POOL.find((p) => p.id === `arch-${key}`);
  if (!c) throw new Error(`no fixture archetype ${key}`);
  return c;
}

// Terms a taster may pick that no fixture archetype links (live
// wset_aroma_terms rows), so group disagreement has something to be.
const EXTRA_TERMS: [string, string][] = [
  ["green bell pepper", "Herbaceous"],
  ["banana", "Tropical fruit"],
  ["coconut", "Oak"],
  ["lavender", "Herbal"],
];

/** term id → { term, group } over every fixture aroma plus EXTRA_TERMS. */
export const LEXICON: AromaLexicon = (() => {
  const out: AromaLexicon = {};
  for (const c of POOL) for (const a of c.aromas) out[a.termId] = { term: a.term, group: a.group };
  for (const [term, group] of EXTRA_TERMS) out[tid(group, term)] = { term, group };
  return out;
})();
