import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { MAX_LEVEL, levelForXp, levelProgress, xpForLevel } from "./curve";

// The parity fixture: 0, every threshold −1 / 0 / +1 for levels 2..60, and
// 1,000,000, generated by a brute-force scan (not by this module).
// scripts/levels.test.mjs checks SQL's level_for_xp against the same file.
const FIXTURE = JSON.parse(
  readFileSync(new URL("./__fixtures__/curve.json", import.meta.url), "utf8"),
) as [number, number][];

describe("xpForLevel", () => {
  it("is 25·L·(L−1): the spec §3.1 table", () => {
    expect([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20, 30, 40, 60].map(xpForLevel)).toEqual([
      0, 50, 150, 300, 500, 750, 1050, 1400, 1800, 2250, 3300, 5250, 9500, 21750, 39000, 88500,
    ]);
  });
  it("treats anything below 1 as level 1", () => {
    expect(xpForLevel(0)).toBe(0);
    expect(xpForLevel(-3)).toBe(0);
  });
});

describe("levelForXp", () => {
  it("matches the fixture on every row", () => {
    expect(FIXTURE).toHaveLength(179);
    for (const [xp, level] of FIXTURE) expect(levelForXp(xp), `xp ${xp}`).toBe(level);
  });
  it("caps at 60 and floors at 1", () => {
    expect(MAX_LEVEL).toBe(60);
    expect(levelForXp(88_500)).toBe(60);
    expect(levelForXp(2_147_483_647)).toBe(60);
    expect(levelForXp(-10)).toBe(1);
    expect(levelForXp(Number.NaN)).toBe(1);
  });
});

describe("levelProgress", () => {
  it("is the owner's example: level 4, 120 of 200 XP to level 5", () => {
    expect(levelProgress(420)).toEqual({ level: 4, into: 120, span: 200, fraction: 0.6, next: 5 });
  });
  it("starts every level at 0", () => {
    expect(levelProgress(0)).toEqual({ level: 1, into: 0, span: 50, fraction: 0, next: 2 });
    expect(levelProgress(50)).toEqual({ level: 2, into: 0, span: 100, fraction: 0, next: 3 });
  });
  it("is full at the top level", () => {
    expect(levelProgress(88_500)).toEqual({ level: 60, into: 0, span: 0, fraction: 1, next: null });
    expect(levelProgress(100_000)).toEqual({ level: 60, into: 11_500, span: 0, fraction: 1, next: null });
  });
});
