-- Burgundy wave 3d2-auxerrois: Grand Auxerrois places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne'),
  'SUBREGION', 'france.bourgogne.grand-auxerrois', 'Grand Auxerrois', 'grand-auxerrois',
  2, 7, 7, 'DRAFT', 100,
  false, null, null
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.grand-auxerrois'),
  'APPELLATION', 'france.bourgogne.grand-auxerrois.irancy', 'Irancy', 'irancy',
  3, 10, 10, 'DRAFT', 101,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.grand-auxerrois'),
  'APPELLATION', 'france.bourgogne.grand-auxerrois.saint-bris', 'Saint-Bris', 'saint-bris',
  3, 10, 10, 'DRAFT', 102,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.grand-auxerrois'),
  'APPELLATION', 'france.bourgogne.grand-auxerrois.vezelay', 'Vézelay', 'vezelay',
  3, 10, 10, 'DRAFT', 103,
  true, 'AOC/AOP', 'communal'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.grand-auxerrois%';
  if v_count <> 4 then
    raise exception 'expected 4 grand-auxerrois places, got %', v_count;
  end if;
end $$;
