-- Alsace Grand Cru articles, part 1 (A-K, 23 crus). Concise learning
-- profiles: soil + village + signature variety per lieu-dit. Part 2 (L-Z)
-- follows in 20260829136000. Insert-only with guards; re-run no-op.
insert into wine_place_articles
  (wine_place_id, description, climate, soils, key_facts, editorial_status)
select p.id, v.descr, v.climate, v.soils, array[v.fact1, v.fact2], 'PUBLISHED'
from (values
  ('altenberg-de-bergbieten',
   'A gypsum-streaked marl slope above Bergbieten in the northern Bas-Rhin - taut, saline Riesling country.',
   'Dry northern sector in the Vosges rain shadow.',
   'Marl and limestone shot through with gypsum.',
   'Riesling leads on the gypsum-marl', 'One of the small northern grands crus'),
  ('altenberg-de-bergheim',
   'The old hill of Bergheim: heavy marl-limestone that gives Gewurztraminer of unusual structure and age-worthiness.',
   'Sheltered mid-Haut-Rhin sector.',
   'Deep clay-marl over limestone.',
   'Gewurztraminer of real structure', 'Blends are legally permitted here since 2005'),
  ('altenberg-de-wolxheim',
   'A limestone-marl rise above Wolxheim near Strasbourg, long prized for delicate, saline Riesling.',
   'Dry northern sector.',
   'Marl-limestone.',
   'Riesling stronghold', 'Once favoured at the imperial court'),
  ('brand',
   'The "burnt hill" of Turckheim: a sun-baked granite amphitheatre whose Riesling is fiery and mineral.',
   'One of the hottest sites in the Haut-Rhin.',
   'Decomposed two-mica granite.',
   'Granite Riesling of great drive', 'The name means burnt - the hill roasts in the sun'),
  ('bruderthal',
   'The "brothers'' valley" above Molsheim - monastic vineyards on marl-limestone giving firm Riesling and Gewurztraminer.',
   'Dry northern sector.',
   'Marl-limestone.',
   'Monastic origins', 'Riesling and Gewurztraminer share the slope'),
  ('eichberg',
   'The oak hill of Eguisheim: a warm, dry marl-limestone slope known for opulent Gewurztraminer and Pinot Gris.',
   'Among the driest sites of Alsace.',
   'Marl-limestone.',
   'Gewurztraminer opulence', 'Very low rainfall even for Alsace'),
  ('engelberg',
   'The angels'' hill above Dahlenheim, a limestone bench in the far north of the appellation.',
   'Dry northern sector.',
   'Marl-limestone over muschelkalk.',
   'Northern outpost of the grand cru family', 'Limestone-driven whites'),
  ('florimont',
   'The hill of flowers near Ingersheim: limestone-marl with a warm microclimate and herb-scented Riesling and Gewurztraminer.',
   'Warm, dry pocket behind Colmar.',
   'Limestone and marl.',
   'Mediterranean flora on the slope', 'Riesling and Gewurztraminer lead'),
  ('frankstein',
   'Four granite knolls above Dambach-la-Ville - the Bas-Rhin''s granite answer to the Haut-Rhin crus, all finesse in Riesling.',
   'Dry, sunny mid-Bas-Rhin.',
   'Two-mica granite.',
   'Granite Riesling of filigree', 'The largest wine commune of the Bas-Rhin'),
  ('froehn',
   'The clay-marl knoll of Zellenberg, ringed by the village - Gewurztraminer with flesh and spice.',
   'Sheltered between Riquewihr and Ribeauville.',
   'Clay and marl.',
   'Gewurztraminer first', 'A small, village-ringed cru'),
  ('furstentum',
   'A steep limestone blade above Kientzheim, hot and dry - Gewurztraminer and Pinot Gris of great concentration.',
   'One of the warmest limestone sites.',
   'Brown limestone, thin and stony.',
   'Furstentum Gewurztraminer is a benchmark', 'Wild boxwood scrub caps the ridge'),
  ('geisberg',
   'Ribeauville''s goat hill: terraced muschelkalk marl and sandstone, a pure Riesling site of legendary tension.',
   'Narrow, sheltered valley mouth.',
   'Muschelkalk marl with sandstone.',
   'Essentially a 100% Riesling cru', 'Terraced and painstaking to work'),
  ('gloeckelberg',
   'The bell hill of Rodern and Saint-Hippolyte - light granite sand giving perfumed, early-charming Gewurztraminer and Pinot Gris.',
   'Sunny slopes below Haut-Koenigsbourg.',
   'Granitic sand.',
   'Gewurztraminer and Pinot Gris lead', 'Shared by two villages'),
  ('goldert',
   'The golden hill of Gueberschwihr, pure marl-limestone - home of Alsace''s greatest Muscat alongside honeyed Gewurztraminer.',
   'Cool-ish, east-facing exposure.',
   'Oolitic marl-limestone.',
   'A rare Muscat stronghold', 'East exposure gives slow, complete ripening'),
  ('hatschbourg',
   'A broad loess-tempered marl-limestone slope over Hattstatt and Voegtlinshoffen - generous Gewurztraminer and Pinot Gris.',
   'Warm mid-Haut-Rhin sector.',
   'Marl-limestone with loess.',
   'Powerful, honeyed styles', 'Shared by two communes'),
  ('hengst',
   'The stallion of Wintzenheim: muscular Gewurztraminer from marl-limestone-sandstone, built to age a decade or more.',
   'Warm and dry behind Colmar.',
   'Marl-limestone with sandstone.',
   'Among the most powerful Gewurztraminers of Alsace', 'Since 2022 also classified for Pinot Noir'),
  ('kaefferkopf',
   'Ammerschwihr''s beetle head - a geological patchwork where, uniquely, BLENDS have historic legitimacy alongside varietals.',
   'Sheltered valley-mouth site.',
   'Granite, limestone and sandstone mosaic.',
   'Blends are part of the decree - rare in Alsace', 'The last lieu-dit promoted (2007)'),
  ('kanzlerberg',
   'Bergheim''s tiny chancellor hill - barely three hectares of heavy gypsum-marl, slow wines that repay patience.',
   'Cool, heavy-soil site.',
   'Gypsum-keuper marl.',
   'One of the smallest grands crus (~3 ha)', 'Dense Riesling and Gewurztraminer'),
  ('kastelberg',
   'Andlau''s castle hill: the only SCHIST grand cru of Alsace, planted since the Middle Ages - dark-toned, smoky, long-lived Riesling.',
   'Steep valley slope.',
   'Steige schist - unique among the 51.',
   'The one schist cru of Alsace', 'Riesling only in practice'),
  ('kessler',
   'The kettle of Guebwiller: a sheltered sandstone-clay hollow, Schlumberger country, famed for rich yet vibrant Gewurztraminer.',
   'Warm, wind-protected hollow.',
   'Sandstone-derived clay-sand.',
   'Gewurztraminer excels in the sheltered bowl', 'Largely worked by Domaines Schlumberger'),
  ('kirchberg-de-barr',
   'Barr''s church hill in the Bas-Rhin: heavy marl-limestone that favours structured Gewurztraminer and firm Riesling.',
   'Dry northern sector.',
   'Marl-limestone.',
   'Structured, slow-opening wines', 'One of the historic Bas-Rhin crus'),
  ('kirchberg-de-ribeauville',
   'The church hill of Ribeauville - terraced marl-sandstone where Riesling and a rare fine Muscat thrive.',
   'Narrow sheltered valley mouth.',
   'Marl with sandstone.',
   'Riesling and noteworthy Muscat', 'Terraced slopes above the town'),
  ('kitterle',
   'Guebwiller''s vertiginous spur - sandstone and volcanic grit worked in terraces; the wine "bites the calves" of those who climb it.',
   'Very steep, sun-drenched spur.',
   'Volcanic-sandstone grit.',
   'Among the steepest vineyards of Alsace', 'Riesling and Gewurztraminer from terraces')
) as v(slug, descr, climate, soils, fact1, fact2)
join wine_places p on p.canonical_key = 'france.alsace.' || v.slug
where not exists (select 1 from wine_place_articles a where a.wine_place_id = p.id);

do $$
declare v_a int;
begin
  select count(*) into v_a from wine_place_articles a
    join wine_places p on p.id = a.wine_place_id
   where p.canonical_key like 'france.alsace%';
  if v_a <> 24 then
    raise exception 'expected 24 alsace articles after part 1 (region + 23 crus), got %', v_a;
  end if;
end $$;
