-- Details-panel content for the places that had none.
--
-- Generated by scripts/wine-map-sources/gen-place-profiles-migration.mjs from
-- data/wine-map/place-profiles.json. Do not hand-edit: the generator resolves every grape name and
-- canonical_key against the live catalog and refuses to emit anything if one of
-- them does not resolve. That check is the point of it. A grape name the
-- catalog does not carry does not raise on insert -- the join simply matches
-- nothing and the row vanishes, leaving a place quietly short of a variety.
--
-- 69 places: germany 20, italy 49.
-- 139 style rows, 149 grape rows, 16 Bereich articles,
-- 2 varieties added to the grape catalog.
--
-- Convention follows the existing region rows (germany.mosel, italy.piemonte):
-- role PRINCIPAL, permitted true, share_pct null. Planting percentages are not
-- invented -- france.champagne carries them because they are published.
--
-- NO TILE RUN. scripts/wine-map-tiles/export.mjs reads wine_places and
-- wine_place_boundaries only; grapes, styles and articles are served by
-- get_wine_place_context at request time. Nothing here changes a tile.

begin;

-- Varieties the content needs that the catalog did not carry.
insert into public.grapes (name, color, description, skin_color)
values ('Bacchus', 'WHITE', 'An aromatic German crossing (Silvaner x Riesling, crossed again with Müller-Thurgau) that ripens early and reliably in cool sites. Grapey and elderflower-scented, low in acid, and a regional speciality of Franken.', 'green-yellow');
insert into public.grapes (name, color, description, skin_color)
values ('Petit Rouge', 'RED', 'Valle d''Aosta''s principal indigenous red, grown in the central valley around Chambave and Torgnon. Light in body, floral and peppery, and the backbone of Enfer d''Arvier and Torrette.', 'blue-black');

-- germany.franken
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.franken';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.franken';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 25, 'The region''s signature and most planted variety', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.franken' and g.name = 'Silvaner';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 21, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.franken' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'A Franken speciality', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.franken' and g.name = 'Bacchus';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.franken' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.franken' and g.name = 'Pinot Noir';

-- germany.saale-unstrut
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.saale-unstrut';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.saale-unstrut';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.saale-unstrut';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 14, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.saale-unstrut' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 14, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.saale-unstrut' and g.name = 'Pinot Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 9, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.saale-unstrut' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.saale-unstrut' and g.name = 'Silvaner';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.saale-unstrut' and g.name = 'Dornfelder';

-- germany.hessische-bergstrasse
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 37, 'Over a third of the vineyard', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 13, 'Grauburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse' and g.name = 'Pinot Blanc';

-- germany.rheingau
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 76, 'About three-quarters of the vineyard', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheingau' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, 13, 'Spätburgunder, concentrated at Assmannshausen', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheingau' and g.name = 'Pinot Noir';

-- germany.ahr.walporzheim-ahrtal
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Ahr''s single Bereich, which covers effectively the whole region: a narrow slate gorge west of the Rhine where Germany makes some of its most serious Pinot Noir. Vineyards are terraced into dark slate and greywacke on slopes reaching sixty degrees, and it is the valley''s heat-trapping walls that let red grapes ripen this far north at all.', 'Sheltered and surprisingly warm for 50°N. The narrow valley holds heat and the dark slate radiates it back at night, which is why red varieties dominate here while the rest of Germany plants white.', 'Devonian slate and greywacke, thin and stony, on terraces cut into very steep slopes.', array['Germany''s red-wine valley — Spätburgunder above all', 'Slate terraces on slopes up to sixty degrees', 'Covers effectively the whole Ahr region', 'Rebuilt after the July 2021 flood']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.ahr.walporzheim-ahrtal';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.ahr.walporzheim-ahrtal';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.ahr.walporzheim-ahrtal';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.ahr.walporzheim-ahrtal' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'An early-ripening Pinot mutation, an Ahr speciality', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.ahr.walporzheim-ahrtal' and g.name = 'Frühburgunder';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.ahr.walporzheim-ahrtal' and g.name = 'Riesling';

-- germany.hessische-bergstrasse.starkenburg
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The main body of the Hessische Bergstraße, running from Darmstadt down through Bensheim and Heppenheim along the western edge of the Odenwald. Almost all of the region''s vineyard is here, most of it Riesling on loess-covered slopes that catch the morning sun.', 'Mild and early, sheltered from the east by the Odenwald and open to the warm Rhine plain.', 'Loess and loam over the crystalline rock of the Odenwald — granite, gneiss and porphyry.', array['Holds almost all of the Bergstraße''s vineyard', 'Bensheim and Heppenheim are its centres', 'Riesling on loess over crystalline rock']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.starkenburg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.starkenburg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.starkenburg';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.starkenburg' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Grauburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.starkenburg' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.starkenburg' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.starkenburg' and g.name = 'Pinot Blanc';

-- germany.hessische-bergstrasse.umstadt
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'A detached pocket of vineyard around Groß-Umstadt, some thirty kilometres north-east of the main Bergstraße and separated from it by the Odenwald. Long known as the Odenwälder Weininsel — the Odenwald''s wine island — it is small, warm, and almost entirely drunk within sight of where it grew.', 'More continental than the Bergstraße proper, sitting in a basin east of the Odenwald rather than on the Rhine plain.', 'Weathered granite and diorite of the Odenwald basement, capped in places by loess and loam.', array['A detached exclave, not joined to the Bergstraße', 'Known as the Odenwälder Weininsel', 'Centred on Groß-Umstadt']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.umstadt';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.umstadt';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.hessische-bergstrasse.umstadt';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.umstadt' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.umstadt' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Grauburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.umstadt' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.hessische-bergstrasse.umstadt' and g.name = 'Pinot Noir';

-- germany.mittelrhein.loreley
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Mittelrhein''s southern and far larger Bereich, following the Rhine gorge through the UNESCO-listed stretch past the Loreley rock. Riesling grows on terraces so steep and so narrow that much of the vineyard has been abandoned over the last century, leaving a small number of growers working some of the most dramatic sites in Germany.', 'Cool and windy in the gorge, with the river moderating the extremes. Ripening depends on slope and aspect more than on anything else.', 'Devonian slate and quartzite, thin over rock, on terraces held by dry-stone walls.', array['Follows the UNESCO-listed Rhine Gorge', 'Riesling on very steep slate terraces', 'Much of the historic vineyard has been abandoned']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mittelrhein.loreley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mittelrhein.loreley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mittelrhein.loreley';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mittelrhein.loreley' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mittelrhein.loreley' and g.name = 'Pinot Noir';

-- germany.mosel.bernkastel
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Middle Mosel, and the heart of the region''s reputation: the loop of river from Trittenheim down through Piesport, Brauneberg, Bernkastel, Wehlen and Zeltingen. Blue Devonian slate, south-facing slopes of extraordinary steepness, and a roll-call of vineyard names — Doctor, Sonnenuhr, Juffer — that set the standard for Riesling everywhere.', 'Cool continental, rescued by the river''s reflected light and by slopes angled to catch every available hour of sun.', 'Blue Devonian slate, weathering to a stony topsoil that holds the day''s heat into the night.', array['The Middle Mosel — the region''s greatest sites', 'Bernkasteler Doctor, Wehlener Sonnenuhr, Brauneberger Juffer', 'Blue Devonian slate', 'Riesling almost to the exclusion of everything else']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mosel.bernkastel';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.bernkastel';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.bernkastel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.bernkastel' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.bernkastel' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.bernkastel' and g.name = 'Pinot Noir';

-- germany.mosel.burg-cochem
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Lower Mosel, from Zell down to Koblenz, and better known to growers as the Terrassenmosel. Here the valley narrows and the slate is worked in small walled terraces rather than open slope — including the Bremmer Calmont, among the steepest vineyards anywhere. Yields are tiny and the work is entirely by hand.', 'Cool, with the narrow valley and dark slate holding what warmth there is. Frost and erosion are constant concerns.', 'Devonian slate in thin terraced pockets, held by dry-stone walls that are themselves a large part of the cost of farming here.', array['The Terrassenmosel — dry-stone terraces, not open slope', 'Bremmer Calmont, among the world''s steepest vineyards', 'Worked entirely by hand']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mosel.burg-cochem';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.burg-cochem';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.burg-cochem';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.burg-cochem' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.burg-cochem' and g.name = 'Pinot Noir';

-- germany.mosel.obermosel
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Upper Mosel, upstream of Trier along the Luxembourg border, and the one part of the region that is not slate at all. Vines grow on Muschelkalk shell-limestone, and the traditional grape is Elbling — ancient, neutral and sharply acidic — much of which becomes Sekt rather than still wine.', 'Cool and continental, marginally warmer than the slate Mosel downstream but without the heat-storing rock that makes those slopes work.', 'Muschelkalk shell-limestone, not slate. That single difference sets the whole Bereich apart from the rest of the Mosel.', array['Limestone, not slate', 'Elbling, an ancient and sharply acidic white', 'Much of the crop becomes Sekt', 'Faces Luxembourg across the river']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mosel.obermosel';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.obermosel';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.obermosel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.obermosel' and g.name = 'Elbling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.obermosel' and g.name = 'Pinot Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.obermosel' and g.name = 'Müller-Thurgau';

-- germany.mosel.ruwer
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'A small tributary valley east of Trier, cooler than the Mosel itself, making Riesling of unusual delicacy — low in alcohol, high in acid, and among the longest-lived wine in Germany. Two estates, Maximin Grünhaus and Karthäuserhof, carry most of its reputation.', 'Cool even by Mosel standards. The Ruwer is a small stream with none of the Mosel''s heat-storing mass, so ripening is late and genuinely marginal.', 'Devonian slate, with some red sandstone and gravel in the valley floor.', array['Cooler than the Mosel proper', 'Riesling of great delicacy and longevity', 'Maximin Grünhaus and Karthäuserhof']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mosel.ruwer';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.ruwer';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.ruwer';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.ruwer' and g.name = 'Riesling';

-- germany.mosel.saar
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Saar joins the Mosel south of Trier, and in a good year makes the most piercing Riesling in Germany — steely, taut and unmistakably cool-climate, with Scharzhofberg as its most famous site. In poor years the grapes barely ripen at all, which is why the Saar''s reputation rests on its best vintages rather than its average one.', 'The coldest corner of the Mosel: exposed, late-ripening, and marginal in the literal sense.', 'Grey Devonian slate, often mixed with quartzite.', array['The coolest and steeliest corner of the Mosel', 'Scharzhofberg', 'Marginal ripening — vintage matters more here than anywhere']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.mosel.saar';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.saar';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.saar';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.mosel.saar';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.mosel.saar' and g.name = 'Riesling';

-- germany.nahe.nahetal
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Nahe''s single Bereich, covering the whole region along the river between Bingen and Bad Kreuznach and up its side valleys. Its defining feature is geological variety — volcanic porphyry, slate, quartzite, sandstone and loam within a few kilometres — which is why Nahe Riesling is so often described as sitting between the Mosel''s delicacy and the Rheingau''s weight.', 'Sheltered by the Hunsrück to the north-west, and among the drier and sunnier parts of German wine country.', 'Unusually varied over a short distance: volcanic porphyry and melaphyre around Schlossböckelheim, slate and quartzite upstream, sandstone and loam downstream.', array['One Bereich covering the whole Nahe', 'Exceptionally varied geology over a few kilometres', 'Riesling between Mosel delicacy and Rheingau weight']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.nahe.nahetal';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.nahe.nahetal';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.nahe.nahetal';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.nahe.nahetal' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.nahe.nahetal' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.nahe.nahetal' and g.name = 'Pinot Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.nahe.nahetal' and g.name = 'Dornfelder';

-- germany.pfalz.mittelhaardt-dt-weinstrasse
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The northern half of the Pfalz and the source of most of its finest wine: a warm strip below the Haardt hills running through Kallstadt, Ungstein, Bad Dürkheim, Wachenheim, Forst, Deidesheim and Ruppertsberg. Forster Kirchenstück and Jesuitengarten and their neighbours give Riesling more weight and ripeness than anywhere further north.', 'One of Germany''s warmest and driest stretches, sheltered by the Haardt. Figs and almonds grow along the Weinstraße.', 'Loam and sandstone with limestone, and at Forst the black basalt that was carted onto the vineyards to hold heat.', array['The Pfalz''s finest strip — Forst, Deidesheim, Wachenheim', 'Riesling with unusual weight and ripeness', 'Basalt at Forst, carted in to hold heat']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse' and g.name = 'Dornfelder';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Grauburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.mittelhaardt-dt-weinstrasse' and g.name = 'Pinot Gris';

-- germany.pfalz.suedl-weinstrasse
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The southern Pfalz, from Neustadt down to the French border, where the Alsace climate begins to make itself felt. Long a source of bulk wine, it has been transformed over the last thirty years into Germany''s most convincing home for Pinot — Weiss-, Grau- and Spätburgunder — alongside increasingly serious Riesling.', 'The warmest stretch of German vineyard, continuous with Alsace across the border.', 'Loess, loam, limestone and coloured sandstone.', array['Germany''s warmest vineyards, continuous with Alsace', 'Transformed from bulk wine to serious Pinot', 'Weiss-, Grau- and Spätburgunder together']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.pfalz.suedl-weinstrasse';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.pfalz.suedl-weinstrasse';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.pfalz.suedl-weinstrasse';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.suedl-weinstrasse' and g.name = 'Pinot Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Grauburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.suedl-weinstrasse' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.suedl-weinstrasse' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.suedl-weinstrasse' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.pfalz.suedl-weinstrasse' and g.name = 'Dornfelder';

-- germany.rheingau.johannisberg
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Rheingau''s single Bereich, named after the hill at Schloss Johannisberg and covering the entire region — the south-facing bank from Hochheim west to Lorch, plus Assmannshausen around the bend where the river turns north again. One Bereich for one of the most tightly drawn wine regions in Germany.', 'Warm for its latitude, sheltered by the Taunus to the north, with the broad river storing heat and lengthening the autumn.', 'Quartzite and slate at the steep western end around Rüdesheim; loess, marl and sandy loam through the gentler middle.', array['One Bereich covering the whole Rheingau', 'Named for the hill at Schloss Johannisberg', 'Riesling on about three-quarters of the vineyard']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.rheingau.johannisberg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau.johannisberg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau.johannisberg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheingau.johannisberg';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheingau.johannisberg' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder, concentrated at Assmannshausen', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheingau.johannisberg' and g.name = 'Pinot Noir';

-- germany.rheinhessen.bingen
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'Rheinhessen''s north-western corner, facing the Nahe across the water at Bingen and the Rheingau across the Rhine to the north. Quartzite and slate on the Scharlachberg give a firmer, more mineral Riesling than most of the gentler country to the south.', 'Mild and dry, with the Nahe and the Rhine meeting here to moderate it.', 'Quartzite and slate on the Scharlachberg; loess and loam elsewhere.', array['Rheinhessen''s north-west corner, at the Nahe''s mouth', 'Quartzite and slate on the Scharlachberg', 'Faces the Rheingau across the river']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.rheinhessen.bingen';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.bingen';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.bingen';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.bingen' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.bingen' and g.name = 'Silvaner';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.bingen' and g.name = 'Müller-Thurgau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.bingen' and g.name = 'Dornfelder';

-- germany.rheinhessen.nierstein
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'The Rheinterrasse — the short east-facing bank between Nackenheim and Oppenheim, and the best vineyard land in Rheinhessen. The Roter Hang, a band of iron-red Rotliegend slate found nowhere else in Germany, runs through Nackenheimer Rothenberg and Niersteiner Pettenthal and Hipping, and gives Riesling an unmistakable smoky depth.', 'Warm and sheltered, with the wide river reflecting light onto slopes that face due east and take the morning sun.', 'The Roter Hang''s red Rotliegend slate and sandstone, unique in German wine, giving way to loess further inland.', array['The Rheinterrasse — Rheinhessen''s finest bank', 'The Roter Hang''s iron-red Rotliegend slate', 'Pettenthal, Hipping, Rothenberg']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.rheinhessen.nierstein';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.nierstein';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.nierstein';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.nierstein' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.nierstein' and g.name = 'Silvaner';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.nierstein' and g.name = 'Pinot Noir';

-- germany.rheinhessen.wonnegau
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'Southern Rheinhessen, between Alzey and Worms, whose name means roughly the delightful district. Anonymous for most of the last century, it is now the address of several of Germany''s most talked-about growers, working Riesling on limestone and clay around Westhofen and Flörsheim-Dalsheim. Worms itself gave the world Liebfraumilch, named for the Liebfrauenstift vineyard beside the church.', 'Warm and dry, and a little more continental than the river terrace to the north-east.', 'Limestone, clay and marl, with loess over much of the gentler land.', array['Westhofen and Flörsheim-Dalsheim', 'Limestone and clay rather than river slate', 'Liebfraumilch takes its name from Worms'' Liebfrauenstift']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'germany.rheinhessen.wonnegau';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.wonnegau';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'germany.rheinhessen.wonnegau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.wonnegau' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.wonnegau' and g.name = 'Silvaner';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Weißburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.wonnegau' and g.name = 'Pinot Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Spätburgunder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'germany.rheinhessen.wonnegau' and g.name = 'Pinot Noir';

-- italy.abruzzo
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.abruzzo';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.abruzzo';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.abruzzo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.abruzzo' and g.name = 'Montepulciano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.abruzzo' and g.name = 'Trebbiano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.abruzzo' and g.name = 'Pecorino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.abruzzo' and g.name = 'Passerina';

-- italy.basilicata
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.basilicata';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.basilicata' and g.name = 'Aglianico';

-- italy.calabria
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.calabria' and g.name = 'Gaglioppo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.calabria' and g.name = 'Greco';

-- italy.campania
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania' and g.name = 'Aglianico';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania' and g.name = 'Fiano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania' and g.name = 'Greco';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania' and g.name = 'Falanghina';

-- italy.emilia-romagna
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna' and g.name = 'Lambrusco di Sorbara';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna' and g.name = 'Lambrusco Grasparossa';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna' and g.name = 'Sangiovese';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna' and g.name = 'Albana';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna' and g.name = 'Trebbiano';

-- italy.lazio
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lazio';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lazio';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio' and g.name = 'Malvasia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio' and g.name = 'Trebbiano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio' and g.name = 'Cesanese';

-- italy.liguria
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.liguria';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.liguria';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria' and g.name = 'Vermentino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria' and g.name = 'Pigato';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria' and g.name = 'Rossese';

-- italy.marche
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche' and g.name = 'Verdicchio';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche' and g.name = 'Montepulciano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche' and g.name = 'Sangiovese';

-- italy.molise
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.molise';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.molise';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.molise' and g.name = 'Montepulciano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.molise' and g.name = 'Tintilia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.molise' and g.name = 'Trebbiano';

-- italy.puglia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.puglia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.puglia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia' and g.name = 'Primitivo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia' and g.name = 'Negroamaro';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia' and g.name = 'Nero di Troia';

-- italy.sardegna
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna' and g.name = 'Cannonau';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna' and g.name = 'Vermentino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna' and g.name = 'Carignano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna' and g.name = 'Vernaccia di Oristano';

-- italy.umbria
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.umbria';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.umbria';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.umbria' and g.name = 'Sangiovese';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.umbria' and g.name = 'Sagrantino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.umbria' and g.name = 'Grechetto';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.umbria' and g.name = 'Trebbiano';

-- italy.valle-d-aosta
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.valle-d-aosta';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.valle-d-aosta';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta' and g.name = 'Petit Rouge';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta' and g.name = 'Nebbiolo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta' and g.name = 'Prié Blanc';

-- italy.friuli
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.friuli';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.friuli';

-- italy.lombardia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lombardia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lombardia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lombardia';

-- italy.piemonte
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.piemonte';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.piemonte';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.piemonte';

-- italy.sicilia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sicilia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sicilia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sicilia';

-- italy.toscana
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.toscana';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.toscana';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.toscana';

-- italy.trentino-alto-adige
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige';

-- italy.veneto
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto';

-- italy.basilicata.vulture
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.basilicata.vulture';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.basilicata.vulture' and g.name = 'Aglianico';

-- italy.calabria.ionio-crotonese
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria.ionio-crotonese';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria.ionio-crotonese';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.calabria.ionio-crotonese' and g.name = 'Gaglioppo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.calabria.ionio-crotonese' and g.name = 'Greco';

-- italy.calabria.locride
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria.locride';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.calabria.locride';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.calabria.locride' and g.name = 'Greco';

-- italy.campania.irpinia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania.irpinia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania.irpinia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania.irpinia' and g.name = 'Aglianico';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania.irpinia' and g.name = 'Fiano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania.irpinia' and g.name = 'Greco';

-- italy.campania.sannio
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania.sannio';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.campania.sannio';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania.sannio' and g.name = 'Falanghina';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.campania.sannio' and g.name = 'Aglianico';

-- italy.emilia-romagna.emilia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna.emilia';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna.emilia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna.emilia' and g.name = 'Lambrusco di Sorbara';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna.emilia' and g.name = 'Lambrusco Grasparossa';

-- italy.emilia-romagna.romagna
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna.romagna';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.emilia-romagna.romagna';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna.romagna' and g.name = 'Sangiovese';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna.romagna' and g.name = 'Albana';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.emilia-romagna.romagna' and g.name = 'Trebbiano';

-- italy.lazio.alta-tuscia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lazio.alta-tuscia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio.alta-tuscia' and g.name = 'Trebbiano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio.alta-tuscia' and g.name = 'Malvasia';

-- italy.lazio.castelli-romani
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lazio.castelli-romani';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio.castelli-romani' and g.name = 'Malvasia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio.castelli-romani' and g.name = 'Trebbiano';

-- italy.lazio.ciociaria
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.lazio.ciociaria';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.lazio.ciociaria' and g.name = 'Cesanese';

-- italy.liguria.riviera-di-levante
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.liguria.riviera-di-levante';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-levante' and g.name = 'Vermentino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-levante' and g.name = 'Bosco';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-levante' and g.name = 'Albarola';

-- italy.liguria.riviera-di-ponente
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.liguria.riviera-di-ponente';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.liguria.riviera-di-ponente';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-ponente' and g.name = 'Pigato';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-ponente' and g.name = 'Vermentino';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.liguria.riviera-di-ponente' and g.name = 'Rossese';

-- italy.marche.castelli-di-jesi
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche.castelli-di-jesi';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche.castelli-di-jesi' and g.name = 'Verdicchio';

-- italy.marche.matelica
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche.matelica';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche.matelica' and g.name = 'Verdicchio';

-- italy.marche.piceno
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche.piceno';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.marche.piceno';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche.piceno' and g.name = 'Montepulciano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche.piceno' and g.name = 'Sangiovese';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.marche.piceno' and g.name = 'Pecorino';

-- italy.molise.basso-molise
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.molise.basso-molise';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.molise.basso-molise';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.molise.basso-molise' and g.name = 'Montepulciano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.molise.basso-molise' and g.name = 'Trebbiano';

-- italy.puglia.central-puglia
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.puglia.central-puglia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia.central-puglia' and g.name = 'Nero di Troia';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia.central-puglia' and g.name = 'Primitivo';

-- italy.puglia.salento
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.puglia.salento';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.puglia.salento';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia.salento' and g.name = 'Negroamaro';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.puglia.salento' and g.name = 'Primitivo';

-- italy.sardegna.gallura
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna.gallura';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna.gallura' and g.name = 'Vermentino';

-- italy.sardegna.oristano
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna.oristano';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna.oristano';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna.oristano' and g.name = 'Vernaccia di Oristano';

-- italy.sardegna.sulcis
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.sardegna.sulcis';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.sardegna.sulcis' and g.name = 'Carignano';

-- italy.valle-d-aosta.basse-vallee
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.valle-d-aosta.basse-vallee';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta.basse-vallee' and g.name = 'Nebbiolo';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta.basse-vallee' and g.name = 'Petit Rouge';

-- italy.valle-d-aosta.valdigne
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.valle-d-aosta.valdigne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'italy.valle-d-aosta.valdigne' and g.name = 'Prié Blanc';

-- italy.trentino-alto-adige.alto-adige
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige.alto-adige';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige.alto-adige';

-- italy.trentino-alto-adige.trentino
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige.trentino';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige.trentino';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.trentino-alto-adige.trentino';

-- italy.veneto.bardolino
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.bardolino';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.bardolino';

-- italy.veneto.conegliano-valdobbiadene-prosecco
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.conegliano-valdobbiadene-prosecco';

-- italy.veneto.soave
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.soave';

-- italy.veneto.valpolicella
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.valpolicella';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'italy.veneto.valpolicella';

do $$
declare r record; n int;
begin
  -- Every row the data asked for is present. A grape name that failed to
  -- resolve would show up here as a short count rather than as silence.
  for r in
    select * from (values
    ('germany.franken', 2, 5, 1),
    ('germany.saale-unstrut', 3, 5, 1),
    ('germany.hessische-bergstrasse', 2, 4, 1),
    ('germany.rheingau', 3, 2, 1),
    ('germany.ahr.walporzheim-ahrtal', 2, 3, 1),
    ('germany.hessische-bergstrasse.starkenburg', 2, 4, 1),
    ('germany.hessische-bergstrasse.umstadt', 2, 4, 1),
    ('germany.mittelrhein.loreley', 2, 2, 1),
    ('germany.mosel.bernkastel', 2, 3, 1),
    ('germany.mosel.burg-cochem', 2, 2, 1),
    ('germany.mosel.obermosel', 2, 3, 1),
    ('germany.mosel.ruwer', 2, 1, 1),
    ('germany.mosel.saar', 3, 1, 1),
    ('germany.nahe.nahetal', 2, 4, 1),
    ('germany.pfalz.mittelhaardt-dt-weinstrasse', 2, 4, 1),
    ('germany.pfalz.suedl-weinstrasse', 2, 5, 1),
    ('germany.rheingau.johannisberg', 3, 2, 1),
    ('germany.rheinhessen.bingen', 2, 4, 1),
    ('germany.rheinhessen.nierstein', 2, 3, 1),
    ('germany.rheinhessen.wonnegau', 2, 4, 1),
    ('italy.abruzzo', 3, 4, 1),
    ('italy.basilicata', 1, 1, 1),
    ('italy.calabria', 3, 2, 1),
    ('italy.campania', 2, 4, 1),
    ('italy.emilia-romagna', 3, 5, 1),
    ('italy.lazio', 2, 3, 1),
    ('italy.liguria', 2, 3, 1),
    ('italy.marche', 2, 3, 1),
    ('italy.molise', 2, 3, 1),
    ('italy.puglia', 2, 3, 1),
    ('italy.sardegna', 3, 4, 1),
    ('italy.umbria', 2, 4, 1),
    ('italy.valle-d-aosta', 2, 3, 1),
    ('italy.friuli', 2, 5, 1),
    ('italy.lombardia', 3, 5, 1),
    ('italy.piemonte', 3, 6, 1),
    ('italy.sicilia', 3, 5, 1),
    ('italy.toscana', 3, 8, 1),
    ('italy.trentino-alto-adige', 3, 7, 1),
    ('italy.veneto', 4, 5, 1),
    ('italy.basilicata.vulture', 1, 1, 1),
    ('italy.calabria.ionio-crotonese', 2, 2, 1),
    ('italy.calabria.locride', 2, 1, 1),
    ('italy.campania.irpinia', 2, 3, 1),
    ('italy.campania.sannio', 2, 2, 1),
    ('italy.emilia-romagna.emilia', 2, 2, 1),
    ('italy.emilia-romagna.romagna', 2, 3, 1),
    ('italy.lazio.alta-tuscia', 1, 2, 1),
    ('italy.lazio.castelli-romani', 1, 2, 1),
    ('italy.lazio.ciociaria', 1, 1, 1),
    ('italy.liguria.riviera-di-levante', 1, 3, 1),
    ('italy.liguria.riviera-di-ponente', 2, 3, 1),
    ('italy.marche.castelli-di-jesi', 1, 1, 1),
    ('italy.marche.matelica', 1, 1, 1),
    ('italy.marche.piceno', 2, 3, 1),
    ('italy.molise.basso-molise', 2, 2, 1),
    ('italy.puglia.central-puglia', 1, 2, 1),
    ('italy.puglia.salento', 2, 2, 1),
    ('italy.sardegna.gallura', 1, 1, 1),
    ('italy.sardegna.oristano', 2, 1, 1),
    ('italy.sardegna.sulcis', 1, 1, 1),
    ('italy.valle-d-aosta.basse-vallee', 1, 2, 1),
    ('italy.valle-d-aosta.valdigne', 1, 1, 1),
    ('italy.trentino-alto-adige.alto-adige', 2, 8, 1),
    ('italy.trentino-alto-adige.trentino', 3, 1, 1),
    ('italy.veneto.bardolino', 2, 3, 1),
    ('italy.veneto.conegliano-valdobbiadene-prosecco', 1, 1, 1),
    ('italy.veneto.soave', 1, 2, 1),
    ('italy.veneto.valpolicella', 2, 4, 1)
    ) as t(key, want_styles, want_grapes, want_article)
  loop
    select count(*) into n from public.wine_place_styles s
      join public.wine_places p on p.id = s.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_styles then
      raise exception '%: % style rows, expected %', r.key, n, r.want_styles;
    end if;
    select count(*) into n from public.wine_place_grapes g
      join public.wine_places p on p.id = g.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_grapes then
      raise exception '%: % grape rows, expected % — a grape name did not resolve', r.key, n, r.want_grapes;
    end if;
    select count(*) into n from public.wine_place_articles a
      join public.wine_places p on p.id = a.wine_place_id where p.canonical_key = r.key;
    if n < r.want_article then
      raise exception '%: no article', r.key;
    end if;
  end loop;

  -- No German or Italian region or subregion is left without styles.
  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION')
     and (p.canonical_key like 'germany.%' or p.canonical_key like 'italy.%')
     and not exists (select 1 from public.wine_place_styles s where s.wine_place_id = p.id);
  if n <> 0 then raise exception '% German/Italian places still have no wine styles', n; end if;

  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION') and p.canonical_key like 'germany.%'
     and not exists (select 1 from public.wine_place_articles a where a.wine_place_id = p.id);
  if n <> 0 then raise exception '% German places still have no article', n; end if;
end $$;

commit;
