-- Details-panel content for the places that had none.
--
-- Generated by scripts/wine-map-sources/gen-place-profiles-migration.mjs from
-- data/wine-map/place-profiles-usa.json. Do not hand-edit: the generator resolves every grape name and
-- canonical_key against the live catalog and refuses to emit anything if one of
-- them does not resolve. That check is the point of it. A grape name the
-- catalog does not carry does not raise on insert -- the join simply matches
-- nothing and the row vanishes, leaving a place quietly short of a variety.
--
-- 16 places: united-states 16.
-- 60 style rows, 95 grape rows, 16 Bereich articles,
-- 1 varieties added to the grape catalog.
--
-- Convention follows the existing region rows (germany.mosel, italy.piemonte):
-- role PRINCIPAL, permitted true, share_pct null. Planting percentages are not
-- invented -- france.champagne carries them because they are published.
--
-- NO TILE RUN. scripts/wine-map-tiles/export.mjs reads wine_places and
-- wine_place_boundaries only; grapes, styles and articles are served by
-- get_wine_place_context at request time. Nothing here changes a tile.

-- No begin;/commit;: the applier owns the transaction (--bare, spec 2026-09-29 D24).

-- Varieties the content needs that the catalog did not carry.
insert into public.grapes (name, color, description, skin_color)
values ('Petite Sirah', 'RED', 'The name California uses for Durif, a French variety. DNA work at UC Davis (Meredith and others, 1999) found that 49 of 53 vines sold as Petite Sirah in California were Durif, and that Durif is most probably a seedling of Peloursin with Syrah as its other parent. It makes deeply coloured, tannic red wine, on its own or in blends.', 'blue-black');

-- united-states
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Wine is made across the United States, but California alone makes about 81 per cent of it. This map covers the four states that matter most for fine wine: California, Washington, Oregon and New York. Wine regions here are American Viticultural Areas (AVAs): grape-growing areas the federal Alcohol and Tobacco Tax and Trade Bureau (TTB) defines by geography, with no rules on grapes, yields or winemaking.', 'Too varied for one description. The West Coast has dry summers: the cold Pacific and coastal fog cool California''s coastal valleys, and the Cascade Mountains leave eastern Washington and Oregon in a dry rain shadow. New York''s vineyards rely on deep lakes and the Atlantic to soften cold continental winters.', 'As varied as the climate: volcanic, marine sedimentary and wind-blown loess soils in Oregon''s Willamette Valley; loess over Ice Age flood gravels and basalt in Washington''s Columbia Valley; decomposed granite in California''s Sierra Foothills; shale and glacial deposits in New York''s Finger Lakes; sandy glacial soils on Long Island.', 'International varieties lead: Cabernet Sauvignon and Chardonnay in California and Washington, Pinot Noir in Oregon, Riesling in the Finger Lakes. Zinfandel has been grown in California since the Gold Rush.', 'Mostly dry reds and whites, usually labelled by grape variety rather than by place. Rosé, sparkling wine, sweet wines and a few fortified wines are made too.', array['TTB lists 280 established AVAs (August 2026); California has 154 of them', 'An AVA name on the label means at least 85% of the grapes come from that AVA (27 CFR 4.25)', 'A state or county name needs 75% of the wine from that place; a grape name needs 75% of that grape (27 CFR 4.23)', 'The first AVA was Augusta, Missouri, established on 20 June 1980', 'California makes about 81% of US wine (Wine Institute)']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states' and g.name = 'Sauvignon Blanc';

-- united-states.california
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'The largest wine state by far: about 81 per cent of the country''s wine, from roughly 540,000 acres of wine grapes. Its AVAs run the length of the state; this map groups them under the North Coast, Central Coast, Sierra Foothills and South Coast AVAs and the Central Valley. Napa Valley, designated in 1981, was California''s first AVA.', 'Mediterranean: mild, wet winters and long, dry summers. Near the coast, marine air and fog from the cold Pacific move inland through gaps and valleys in the Coast Ranges, so the coolest vineyards lie closest to the ocean and the warmest in the inland valleys and the foothills.', 'Every kind, changing over short distances: alluvial valley floors, volcanic soils in Napa and Lake County, calcareous soils in Paso Robles, decomposed granite in the Sierra Foothills and Temecula Valley, and deep sandy loam washed down from the Sierra Nevada around Lodi.', 'Cabernet Sauvignon and Chardonnay are the two most planted wine grapes. Pinot Noir comes from the cooler coast, Zinfandel from Lodi, Sonoma and the Sierra Foothills, and Petite Sirah (Durif) is widely grown for deep-coloured reds.', 'Mostly dry varietal reds and whites, from cool-coast Pinot Noir and Chardonnay to ripe Cabernet Sauvignon and Zinfandel. Sparkling wine and rosé are made too, and sweet and fortified wines in the Central Valley.', array['About 540,000 acres of wine grapes (CDFA estimate for 2025)', '154 of the 280 US AVAs lie wholly or partly in California (TTB)', 'Wine labelled California must be made only from California grapes, stricter than the federal 75% (17 CCR 17015)', 'At the 1976 Paris tasting, a 1973 Stag''s Leap Cabernet Sauvignon and a 1973 Chateau Montelena Chardonnay placed first', 'Napa Valley, designated in 1981, was California''s first AVA']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Sauvignon Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Durif', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california' and g.name = 'Petite Sirah';

-- united-states.california.central-coast
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'A long umbrella AVA, established in 1985, that runs from the San Francisco Bay area south to Santa Barbara County. It takes in, among others, the Santa Cruz Mountains, Livermore Valley, the Monterey AVAs, Paso Robles and its eleven districts, Edna Valley, and the Santa Barbara AVAs from Santa Maria Valley to Sta. Rita Hills.', 'Cooled by the Pacific along its whole length. Marine air from Monterey Bay gives Monterey County one of the longest growing seasons in California. In Santa Barbara County the mountains run east to west, so the valleys open straight onto the ocean and draw fog and breezes inland; Paso Robles, further from the sea, has wide swings between day and night.', 'Mixed: granite, marine sediments and volcanic rock. Paso Robles stands out for calcareous soils with a high pH of 7.4 to 8.6, and calcareous shale on its western hills.', 'Chardonnay and Pinot Noir in the cool western valleys of Monterey and Santa Barbara; Cabernet Sauvignon, Syrah, Zinfandel and Grenache in warmer Paso Robles and the eastern Santa Barbara valleys.', 'Dry reds and whites, from cool-climate Pinot Noir and Chardonnay to Rhône and Bordeaux varieties inland; rosé and sparkling wine too.', array['Established 1985 (27 CFR 9.75)', 'Covers parts of ten counties, from San Francisco and Alameda south to Santa Barbara', 'Paso Robles has eleven nested AVAs, all established in 2014 (TTB)', 'Livermore Valley vineyards date from the early 1880s (Wente and Concannon)', 'Santa Barbara County''s transverse valleys run east to west, open to Pacific fog']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california.central-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-coast';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-coast' and g.name = 'Grenache';

-- united-states.california.central-valley
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Central Valley is a grouping on this map, not an AVA. It gathers the eleven AVAs of the Sacramento and San Joaquin valleys that sit in no larger umbrella AVA: Lodi, Clarksburg, Madera, Capay Valley, Diablo Grande, Dunnigan Hills, Paulsell Valley, River Junction, Salado Creek, Tracy Hills and Winters Highlands. Lodi lies where the two valleys meet, and grapes came to it with the Gold Rush.', 'Hot, dry summers. Around Lodi and Clarksburg, breezes from San Francisco Bay come up through the Carquinez Strait and the Sacramento-San Joaquin Delta and cool the vineyards in the evening; further south, around Madera, the valley is warmer, which suits the sweet and fortified wines made there.', 'Around Lodi, deep, well-drained sandy loams of granite washed down from the Sierra Nevada by the Mokelumne River; elsewhere the valley floor is alluvial.', 'Zinfandel above all around Lodi, much of it from old bush vines, with Cabernet Sauvignon, Chardonnay and Petite Sirah. Clarksburg is known for Chenin Blanc, and Madera for Muscat.', 'Dry reds and whites, led by Lodi Zinfandel, plus sweet Muscat and port-style fortified wines from Madera.', array['A navigation grouping on this map, with eleven member AVAs; it has no legal status', 'Lodi has thousands of acres of old bush vines, most of them Zinfandel, many dry-farmed and own-rooted', 'Clarksburg, in the Sacramento River Delta, is known for Chenin Blanc', 'In Madera, Ficklin Vineyards has made port-style wine since 1948 and Quady Winery makes sweet Muscat']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california.central-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.central-valley';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Durif', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Petite Sirah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Clarksburg''s white', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Chenin Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Madera''s sweet wines', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.central-valley' and g.name = 'Muscat';

-- united-states.california.north-coast
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'The umbrella AVA for California''s northern coastal counties, established in 1983. It covers parts of Lake, Marin, Mendocino, Napa, Solano and Sonoma counties and contains, among many others, Napa Valley, Russian River Valley, Sonoma Coast and Anderson Valley. More than half of California''s wineries are in this region.', 'Mediterranean, and cooler toward the ocean. Marine air and fog come in from the Pacific and San Francisco Bay, so the Sonoma coast and the Carneros district by the bay are cool, while valleys and ridges further inland are warmer.', 'Varied over short distances: alluvial valley floors, volcanic soils on the ridges, and red volcanic soils around Mount Konocti, a dormant volcano, in Lake County.', 'Cabernet Sauvignon above all in Napa Valley; Chardonnay and Pinot Noir in the cooler districts near the coast and the bay; Zinfandel in Sonoma and Mendocino.', 'Dry reds and whites, from Napa Cabernet Sauvignon to coastal Pinot Noir and Chardonnay, and sparkling wine from the cooler districts.', array['Established 1983 (27 CFR 9.30)', 'Covers parts of Lake, Marin, Mendocino, Napa, Solano and Sonoma counties', 'Contains Napa Valley, California''s first AVA (1981), which grows about 4% of the state''s wine grapes', 'Home to more than half of California''s wineries (Discover California Wines)']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california.north-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.north-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.north-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.north-coast';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.north-coast' and g.name = 'Sauvignon Blanc';

-- united-states.california.sierra-foothills
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'A long AVA on the western slopes of the Sierra Nevada, established in 1987 across eight counties from Yuba in the north to Mariposa in the south. Vines came with the Gold Rush, and some of the oldest Zinfandel vineyards still in production are here. It contains El Dorado, Fair Play, California Shenandoah Valley, Fiddletown and North Yuba.', 'Warm, dry summers, tempered by height: nearly all its Zinfandel vineyards sit between about 1,200 and 3,500 feet, where nights are cooler than on the valley floor below.', 'Largely decomposed granite on the foothill slopes, well drained, with volcanic soils in parts of Amador and El Dorado counties.', 'Zinfandel, about 40 per cent of the vineyard acreage, much of it from old vines; Barbera, Syrah and Petite Sirah are the other main reds.', 'Mostly dry reds, above all Zinfandel, with some whites.', array['Established 1987 (27 CFR 9.120)', 'Eight counties: Yuba, Nevada, Placer, El Dorado, Amador, Calaveras, Tuolumne and Mariposa', 'Zinfandel is about 40% of the vineyard acreage (ZAP)', 'The Original Grandpere Vineyard, planted in 1869, is the oldest documented Zinfandel vineyard still producing']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california.sierra-foothills';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.sierra-foothills';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.sierra-foothills';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.sierra-foothills' and g.name = 'Zinfandel';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.sierra-foothills' and g.name = 'Barbera';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.sierra-foothills' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Durif', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.sierra-foothills' and g.name = 'Petite Sirah';

-- united-states.california.south-coast
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'The umbrella AVA for Southern California''s vineyards, established in 1985 in parts of Orange, Riverside and San Diego counties. Its main wine district is Temecula Valley, inland in Riverside County; Ramona Valley and San Pasqual Valley are the other AVAs inside it.', 'Warm and sunny, cooled where the coastal mountains open. In Temecula Valley, hot air rising over the desert draws Pacific air in through the Rainbow Gap, so warm days are followed by cool nights.', 'Temecula Valley''s vineyards are largely on well-drained decomposed granite.', 'Cabernet Sauvignon, Syrah, Chardonnay and Sauvignon Blanc, among some thirty varieties grown in Temecula Valley, including Sangiovese, Vermentino and Barbera.', 'Dry reds, whites and rosé, much of it sold at the wineries themselves.', array['Established 1985 (27 CFR 9.104)', 'Covers parts of Orange, Riverside and San Diego counties', 'Temecula Valley sits between the Pacific and the desert, about an hour north-east of San Diego', 'Contains the Temecula Valley, Ramona Valley and San Pasqual Valley AVAs']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.california.south-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.south-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.south-coast';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.california.south-coast';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.south-coast' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.south-coast' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.south-coast' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.california.south-coast' and g.name = 'Sauvignon Blanc';

-- united-states.new-york
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Most of New York''s vineyards grow native and hybrid grapes, above all Concord, for juice and jam: Concord makes up about 80 per cent of the state''s grape tonnage. Its fine wine comes from European vinifera grapes, planted with success only from the 1950s, chiefly in the Finger Lakes and on Long Island. The state has eleven AVAs, including Lake Erie and the Hudson River Region.', 'Continental, with cold winters once thought too harsh for European vines. The wine regions sit beside water: deep lakes store summer heat and delay spring frost in the Finger Lakes, and the Atlantic and Long Island Sound keep Long Island''s winters milder than the rest of the state.', 'Glacial in origin almost everywhere: grey shale and silty limestone bedrock under varied glacial soils in the Finger Lakes, and sandy, well-drained glacial moraine on Long Island.', 'Riesling leads the vinifera in the Finger Lakes, with Chardonnay, Cabernet Franc, Pinot Noir and Gewürztraminer; Merlot and Cabernet Franc lead on Long Island. Concord, Niagara and hybrids such as Seyval Blanc cover much of the rest of the state.', 'Dry to sweet Riesling and other aromatic whites, lighter-bodied reds, rosé and traditional-method sparkling wine.', array['Eleven AVAs lie wholly or partly in New York (TTB)', 'Concord is about 80% of New York''s grape tonnage, grown mostly for juice and jam (Cornell, 2018)', 'The Lake Erie region is the largest and oldest Concord-growing area in the world', 'Konstantin Frank planted vinifera on Keuka Lake from 1958 and released his first wines in 1962', 'Long Island''s first vineyard was planted in 1973']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Gewürztraminer';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Sold as Lemberger', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york' and g.name = 'Blaufränkisch';

-- united-states.new-york.finger-lakes
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'An AVA in upstate New York, established in 1982, around a series of long, narrow glacial lakes, with Canandaigua, Keuka, Seneca and Cayuga at the heart of its wine growing. It has about 10,700 acres of vineyard and 144 wineries, and is known above all for Riesling. Seneca Lake and Cayuga Lake are AVAs within it.', 'Cool and continental. The lakes, some of the deepest in the United States, store heat from March to August and give it back for the rest of the year, which delays spring frost and stretches the growing season to about 195 days.', 'Devonian bedrock of grey shale and silty limestone, or of shale, siltstone, sandstone and limestone together, under glacial soils that change from site to site.', 'Riesling first, then Cabernet Franc, Pinot Noir, Gewürztraminer and Chardonnay; Lemberger (Blaufränkisch) is a local red. Native and hybrid grapes are still widely grown.', 'Riesling from dry to sweet, other aromatic whites, light reds, rosé and sparkling wine.', array['Established 1982 (27 CFR 9.34)', 'About 10,700 acres of vineyard and 144 wineries (NYWGF)', 'Contains the Cayuga Lake (1988) and Seneca Lake (2003) AVAs', 'Growing season about 195 days, lengthened by the lakes', 'Konstantin Frank''s vinifera plantings on Keuka Lake began in 1958']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.finger-lakes';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Gewürztraminer';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Sold as Lemberger', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.finger-lakes' and g.name = 'Blaufränkisch';

-- united-states.new-york.long-island
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'The Long Island AVA, established in 2001, covers Nassau and Suffolk counties, and its vineyards lie at the eastern end, on the North Fork and the South Fork. Alex and Louisa Hargrave planted the first vineyard at Cutchogue in 1973; the island now has about 1,815 acres of vines. It contains the North Fork of Long Island and The Hamptons, Long Island AVAs, both older than it.', 'Maritime. The Atlantic, Long Island Sound and Peconic Bay moderate the temperature: long, warm summers, mild springs and autumns, winters much milder than upstate, and a growing season of about 225 days.', 'Glacial and sandy: deep, well-drained soils on the northern moraine, and coarser, fast-draining soils on the southern one.', 'Merlot and Cabernet Franc lead the reds, with Cabernet Sauvignon; Chardonnay and Sauvignon Blanc lead the whites.', 'Medium-bodied reds from Bordeaux varieties, crisp whites, rosé and sparkling wine.', array['Established 2001 (27 CFR 9.170); The Hamptons (1985) and North Fork (1986) AVAs came first', 'First vineyard planted in 1973, at Cutchogue on the North Fork', 'About 1,815 acres of vineyard and 82 wineries (NYWGF)', 'Growing season about 225 days']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.new-york.long-island';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.long-island';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.long-island';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.long-island';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.new-york.long-island';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.long-island' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.long-island' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.long-island' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.long-island' and g.name = 'Sauvignon Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.new-york.long-island' and g.name = 'Cabernet Sauvignon';

-- united-states.oregon
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Oregon''s wine is shaped by one grape: Pinot Noir covers 60 per cent of the state''s 47,343 planted acres. The Willamette Valley, where David Lett planted the first Pinot Noir in 1965, holds the largest concentration of its wineries and vineyards; Southern Oregon, warmer and drier, grows a wider range. Oregon has 23 AVAs.', 'West of the Cascades, the Willamette Valley has cool, wet winters and warm, dry summers, and Southern Oregon is warmer and drier. In the north-east, the Columbia Valley and Walla Walla Valley AVAs cross the state line from Washington into dry country east of the mountains.', 'In the Willamette Valley, red volcanic Jory soils formed from Columbia River basalts, marine sedimentary soils such as Willakenzie, and wind-blown loess; in Southern Oregon, marine sediments, alluvial gravels and volcanic soils.', 'Pinot Noir is 60 per cent of the vineyard; Pinot Gris and Chardonnay follow in the Willamette Valley, and Southern Oregon adds Syrah, Cabernet Sauvignon, Merlot, Viognier and Tempranillo.', 'Mostly dry Pinot Noir, Pinot Gris and Chardonnay; rosé and sparkling wine are made from the same grapes.', array['47,343 planted acres in 2024, 60% of them Pinot Noir (Oregon Vineyard and Winery Census)', '23 AVAs; Mount Pisgah, Polk County, Oregon became the 23rd in 2022', 'A varietal wine must be at least 90% that grape, with 18 varieties allowed at 75% (Oregon rules)', 'An Oregon AVA or county name needs 95% of the grapes from it and 100% from Oregon', 'David Lett planted the Willamette Valley''s first Pinot Noir in 1965']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon' and g.name = 'Tempranillo';

-- united-states.oregon.southern-oregon
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'An umbrella AVA established in 2004 over Oregon''s south-west, from south of Eugene to the California border. It joins the Umpqua Valley and Rogue Valley AVAs with Applegate Valley, Elkton Oregon and Red Hill Douglas County. Warmer and drier than the Willamette Valley, it grows a wider range of grapes on about 9,240 planted acres.', 'The warmest and driest part of western Oregon, broken into many microclimates by valleys and hillsides. The Umpqua Valley is warmer than the Willamette Valley but cooler than the Rogue Valley further south.', 'Marine sedimentary soils, alluvial gravels and volcanic soils, varying from valley to valley.', 'Pinot Noir and Pinot Gris, as elsewhere in Oregon, alongside grapes that need more warmth: Syrah, Cabernet Sauvignon, Merlot, Viognier and Tempranillo.', 'Dry reds and whites, from Pinot Noir to Syrah, Cabernet Sauvignon and Tempranillo, and rosé.', array['Established 2004 (27 CFR 9.179), in Douglas, Jackson and Josephine counties', 'About 2,283,600 acres in all, of which about 9,240 are planted (Oregon Wine Board)', 'Contains the Umpqua Valley, Rogue Valley, Applegate Valley, Elkton Oregon and Red Hill Douglas County AVAs', 'Abacela planted Tempranillo in the Umpqua Valley in 1995, the first varietal Tempranillo made in the Pacific Northwest']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.oregon.southern-oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.southern-oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.southern-oregon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.southern-oregon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Viognier';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.southern-oregon' and g.name = 'Tempranillo';

-- united-states.oregon.willamette-valley
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Oregon''s main wine region, about 150 miles long from Portland south to Eugene, and an AVA since 1983. It has 25,450 acres under vine, more than 700 wineries and eleven nested AVAs, from the Dundee Hills and Eola-Amity Hills to Mount Pisgah, Polk County. Pinot Noir is its grape.', 'Cool, with cool, wet winters and warm, dry summers, and warm days and cool nights that keep acidity in the grapes. The Coast Range to the west and the Cascades to the east shelter the valley; the Van Duzer Corridor, a gap in the Coast Range, lets afternoon ocean winds into its western side.', 'Three main types on the hillsides: red volcanic Jory soils formed from Columbia River basalts, as in the Dundee Hills; marine sedimentary soils such as Willakenzie, as in Yamhill-Carlton; and wind-blown Laurelwood loess in the Chehalem Mountains. Most vineyards sit above about 200 feet, clear of the Missoula flood soils on the valley floor.', 'Pinot Noir leads, followed by Pinot Gris, Chardonnay and Riesling; roughly 30 per cent of the valley''s grapes are now other varieties, Pinot Blanc among them.', 'Dry Pinot Noir above all, with Pinot Gris and Chardonnay whites, and rosé and sparkling wine from the same grapes.', array['Established 1983 (27 CFR 9.90)', '25,450 acres under vine (Oregon Wine Board)', 'Eleven nested AVAs, the newest Mount Pisgah, Polk County, Oregon (2022)', 'David Lett planted the first Pinot Noir in the Dundee Hills in 1966, at The Eyrie Vineyards', 'Lett''s 1975 Pinot Noir placed highly at the 1979 Gault-Millau Wine Olympiad in Paris']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.oregon.willamette-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.willamette-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.willamette-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.willamette-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.oregon.willamette-valley';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.willamette-valley' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.willamette-valley' and g.name = 'Pinot Gris';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.willamette-valley' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.willamette-valley' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.oregon.willamette-valley' and g.name = 'Pinot Blanc';

-- united-states.washington
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'The second-largest wine-producing state, with about 35,000 acres of wine grapes and close to 1,000 wineries. Almost all of it lies east of the Cascade Mountains: over 99 per cent of the state''s vineyard acreage is in the Columbia Valley AVA. Washington has 22 AVAs; Columbia Valley, Columbia Gorge and Walla Walla Valley are shared with Oregon, and Lewis-Clark Valley with Idaho.', 'East of the Cascades the vineyards sit in a rain shadow, with 6 to 8 inches of rain a year in the Columbia Valley, and are irrigated from the Columbia River and its tributaries. Summer days bring up to 17 hours of sunlight, and days and nights differ by 30 to 40°F. West of the Cascades, Puget Sound is cool and wet.', 'Wind-blown loess and sand over gravel and slackwater sediment left by the Ice Age floods, with basalt beneath. Most vines grow on their own roots rather than grafted rootstock, since phylloxera survives poorly in very sandy soils.', 'Cabernet Sauvignon, Chardonnay, Merlot, Riesling and Syrah lead among more than 80 varieties grown, with Cabernet Franc and Sauvignon Blanc behind them.', 'Mostly dry reds and whites, the reds led by Cabernet Sauvignon, Merlot and Syrah; Riesling is made from dry to sweet, and some rosé.', array['The second-largest wine-producing state in the US (Washington State Wine Commission)', 'About 35,000 acres of wine grapes, 985 licensed wineries and 22 AVAs', 'Over 99% of the state''s vineyard acreage is in the Columbia Valley AVA', 'Cabernet Sauvignon was first planted in 1941, Riesling in 1961, Chardonnay in 1964 and Merlot in 1965 (WSWC)']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.washington';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington' and g.name = 'Sauvignon Blanc';

-- united-states.washington.columbia-valley
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'Washington''s inland AVA, established in 1984, covering more than 11 million acres of central and south-eastern Washington and a part of north-central Oregon. It holds over 99 per cent of Washington''s vineyard acreage and most of the state''s other AVAs, among them Yakima Valley, Red Mountain, Horse Heaven Hills and Walla Walla Valley.', 'Arid and semi-arid, in the rain shadow of the Cascades, with 6 to 8 inches of rain a year; the vineyards are irrigated from the Columbia River and its tributaries. Long summer days of sunlight and a wide gap between day and night temperatures.', 'Loess, wind-blown sand and silt, over gravel and slackwater sediment laid down by the Ice Age floods, with basalt beneath.', 'Cabernet Sauvignon, Chardonnay, Merlot, Riesling and Syrah lead.', 'Dry reds and whites above all, and Riesling in styles from dry to sweet.', array['Established 1984 (27 CFR 9.74); spans Washington and Oregon', 'More than 11 million acres in all (Washington State Wine Commission)', 'Over 99% of Washington''s vineyard acreage lies inside it', 'Contains Yakima Valley, Washington''s first AVA (1983), and Red Mountain (2001)']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.washington.columbia-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.columbia-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.columbia-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.columbia-valley';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.columbia-valley';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.columbia-valley' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.columbia-valley' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.columbia-valley' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.columbia-valley' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.columbia-valley' and g.name = 'Syrah';

-- united-states.washington.puget-sound
insert into public.wine_place_articles (wine_place_id, description, climate, soils, grape_varieties, wine_styles, key_facts, editorial_status)
select id, 'An AVA west of the Cascades, established in 1995 in the lowlands around Puget Sound and its islands. It is large, about 5.5 million acres, but has only about 121 acres of vines, and it grows varieties seen nowhere else in the state, such as Madeleine Angevine and Siegerrebe.', 'Temperate and maritime: Washington''s coolest and wettest growing region, with 15 to 60 inches of rain a year, most of it between November and April.', 'Laid down by the ice sheet that shaped the Sound: glacial till, which gives sandy, rocky, well-drained soils, and outwash gravels and sands left by meltwater streams.', 'Pinot Noir and Riesling are the main grapes, with Müller-Thurgau, Madeleine Angevine, Siegerrebe and other early-ripening varieties.', 'Light, crisp whites and light reds, mostly Pinot Noir.', array['Established 1995 (27 CFR 9.151)', 'About 121 planted acres within 5.5 million acres (Washington State Wine Commission)', 'Washington''s coolest and wettest growing region', 'Grows Madeleine Angevine and Siegerrebe, seen nowhere else in the state']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'united-states.washington.puget-sound';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.puget-sound';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'united-states.washington.puget-sound';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.puget-sound' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.puget-sound' and g.name = 'Riesling';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'united-states.washington.puget-sound' and g.name = 'Müller-Thurgau';

do $$
declare r record; n int;
begin
  -- Every row the data asked for is present. A grape name that failed to
  -- resolve would show up here as a short count rather than as silence.
  for r in
    select * from (values
    ('united-states', 5, 8, 1),
    ('united-states.california', 4, 8, 1),
    ('united-states.california.central-coast', 4, 6, 1),
    ('united-states.california.central-valley', 4, 6, 1),
    ('united-states.california.north-coast', 3, 6, 1),
    ('united-states.california.sierra-foothills', 2, 4, 1),
    ('united-states.california.south-coast', 3, 4, 1),
    ('united-states.new-york', 5, 7, 1),
    ('united-states.new-york.finger-lakes', 5, 6, 1),
    ('united-states.new-york.long-island', 4, 5, 1),
    ('united-states.oregon', 4, 7, 1),
    ('united-states.oregon.southern-oregon', 3, 8, 1),
    ('united-states.oregon.willamette-valley', 4, 5, 1),
    ('united-states.washington', 4, 7, 1),
    ('united-states.washington.columbia-valley', 4, 5, 1),
    ('united-states.washington.puget-sound', 2, 3, 1)
    ) as t(key, want_styles, want_grapes, want_article)
  loop
    select count(*) into n from public.wine_place_styles s
      join public.wine_places p on p.id = s.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_styles then
      raise exception '%: % style rows, expected %', r.key, n, r.want_styles;
    end if;
    select count(*) into n from public.wine_place_grapes g
      join public.wine_places p on p.id = g.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_grapes then
      raise exception '%: % grape rows, expected % — a grape name did not resolve', r.key, n, r.want_grapes;
    end if;
    select count(*) into n from public.wine_place_articles a
      join public.wine_places p on p.id = a.wine_place_id where p.canonical_key = r.key;
    if n < r.want_article then
      raise exception '%: no article', r.key;
    end if;
  end loop;

  -- No region or subregion in united-states is left without wine styles.
  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION')
     and (p.canonical_key like 'united-states.%')
     and not exists (select 1 from public.wine_place_styles s where s.wine_place_id = p.id);
  if n <> 0 then raise exception '% places still have no wine styles', n; end if;

  -- Country level too: germany and spain always had rows and the other three
  -- did not, which was an inconsistency with no reason behind it.
  select count(*) into n from public.wine_places p
   where p.kind = 'COUNTRY' and (p.canonical_key like 'united-states')
     and not exists (select 1 from public.wine_place_styles s where s.wine_place_id = p.id);
  if n <> 0 then raise exception '% countries still have no wine styles', n; end if;

  -- ...or without an article.
  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION')
     and (p.canonical_key like 'united-states.%')
     and not exists (select 1 from public.wine_place_articles a where a.wine_place_id = p.id);
  if n <> 0 then raise exception '% places still have no article', n; end if;
end $$;

