-- Burgundy wave 3d3-maconnais: Mâconnais places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne'),
  'SUBREGION', 'france.bourgogne.maconnais', 'Mâconnais', 'maconnais',
  2, 7, 7, 'DRAFT', 115,
  false, null, null
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.macon', 'Mâcon', 'macon',
  3, 10, 10, 'DRAFT', 116,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.vire-clesse', 'Viré-Clessé', 'vire-clesse',
  3, 10, 10, 'DRAFT', 117,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.pouilly-fuisse', 'Pouilly-Fuissé', 'pouilly-fuisse',
  3, 10, 10, 'DRAFT', 118,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru', 'Pouilly-Fuissé 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 119,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.pouilly-vinzelles', 'Pouilly-Vinzelles', 'pouilly-vinzelles',
  3, 10, 10, 'DRAFT', 120,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.pouilly-loche', 'Pouilly-Loché', 'pouilly-loche',
  3, 10, 10, 'DRAFT', 121,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais'),
  'APPELLATION', 'france.bourgogne.maconnais.saint-veran', 'Saint-Véran', 'saint-veran',
  3, 10, 10, 'DRAFT', 122,
  true, 'AOC/AOP', 'communal'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.maconnais%';
  if v_count <> 8 then
    raise exception 'expected 8 maconnais places, got %', v_count;
  end if;
end $$;
