-- Burgundy wave 3d1: Côte de Beaune places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne'),
  'SUBREGION', 'france.bourgogne.cote-de-beaune', 'Côte de Beaune', 'cote-de-beaune',
  2, 7, 7, 'DRAFT', 53,
  false, null, null
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.ladoix', 'Ladoix', 'ladoix',
  3, 10, 10, 'DRAFT', 54,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.ladoix'),
  'SITE', 'france.bourgogne.cote-de-beaune.ladoix.premier-cru', 'Ladoix 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 55,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.aloxe-corton', 'Aloxe-Corton', 'aloxe-corton',
  3, 10, 10, 'DRAFT', 56,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.aloxe-corton'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.aloxe-corton.corton', 'Corton', 'corton',
  4, 13, 13, 'DRAFT', 57,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.aloxe-corton'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.aloxe-corton.corton-charlemagne', 'Corton-Charlemagne', 'corton-charlemagne',
  4, 13, 13, 'DRAFT', 58,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.aloxe-corton'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.aloxe-corton.charlemagne', 'Charlemagne', 'charlemagne',
  4, 13, 13, 'DRAFT', 59,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.aloxe-corton'),
  'SITE', 'france.bourgogne.cote-de-beaune.aloxe-corton.premier-cru', 'Aloxe-Corton 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 60,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.pernand-vergelesses', 'Pernand-Vergelesses', 'pernand-vergelesses',
  3, 10, 10, 'DRAFT', 61,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.pernand-vergelesses'),
  'SITE', 'france.bourgogne.cote-de-beaune.pernand-vergelesses.premier-cru', 'Pernand-Vergelesses 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 62,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.savigny-les-beaune', 'Savigny-lès-Beaune', 'savigny-les-beaune',
  3, 10, 10, 'DRAFT', 63,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.savigny-les-beaune'),
  'SITE', 'france.bourgogne.cote-de-beaune.savigny-les-beaune.premier-cru', 'Savigny-lès-Beaune 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 64,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.chorey-les-beaune', 'Chorey-lès-Beaune', 'chorey-les-beaune',
  3, 10, 10, 'DRAFT', 65,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.beaune', 'Beaune', 'beaune',
  3, 10, 10, 'DRAFT', 66,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.beaune'),
  'SITE', 'france.bourgogne.cote-de-beaune.beaune.premier-cru', 'Beaune 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 67,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.pommard', 'Pommard', 'pommard',
  3, 10, 10, 'DRAFT', 68,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.pommard'),
  'SITE', 'france.bourgogne.cote-de-beaune.pommard.premier-cru', 'Pommard 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 69,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.volnay', 'Volnay', 'volnay',
  3, 10, 10, 'DRAFT', 70,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.volnay'),
  'SITE', 'france.bourgogne.cote-de-beaune.volnay.premier-cru', 'Volnay 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 71,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.monthelie', 'Monthélie', 'monthelie',
  3, 10, 10, 'DRAFT', 72,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.monthelie'),
  'SITE', 'france.bourgogne.cote-de-beaune.monthelie.premier-cru', 'Monthélie 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 73,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.auxey-duresses', 'Auxey-Duresses', 'auxey-duresses',
  3, 10, 10, 'DRAFT', 74,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.auxey-duresses'),
  'SITE', 'france.bourgogne.cote-de-beaune.auxey-duresses.premier-cru', 'Auxey-Duresses 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 75,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.saint-romain', 'Saint-Romain', 'saint-romain',
  3, 10, 10, 'DRAFT', 76,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.meursault', 'Meursault', 'meursault',
  3, 10, 10, 'DRAFT', 77,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.meursault'),
  'SITE', 'france.bourgogne.cote-de-beaune.meursault.premier-cru', 'Meursault 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 78,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.puligny-montrachet', 'Puligny-Montrachet', 'puligny-montrachet',
  3, 10, 10, 'DRAFT', 79,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.puligny-montrachet'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.puligny-montrachet.montrachet', 'Montrachet', 'montrachet',
  4, 13, 13, 'DRAFT', 80,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.puligny-montrachet'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.puligny-montrachet.chevalier-montrachet', 'Chevalier-Montrachet', 'chevalier-montrachet',
  4, 13, 13, 'DRAFT', 81,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.puligny-montrachet'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.puligny-montrachet.bienvenues-batard-montrachet', 'Bienvenues-Bâtard-Montrachet', 'bienvenues-batard-montrachet',
  4, 13, 13, 'DRAFT', 82,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.puligny-montrachet'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.puligny-montrachet.batard-montrachet', 'Bâtard-Montrachet', 'batard-montrachet',
  4, 13, 13, 'DRAFT', 83,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.puligny-montrachet'),
  'SITE', 'france.bourgogne.cote-de-beaune.puligny-montrachet.premier-cru', 'Puligny-Montrachet 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 84,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.chassagne-montrachet', 'Chassagne-Montrachet', 'chassagne-montrachet',
  3, 10, 10, 'DRAFT', 85,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.chassagne-montrachet'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.chassagne-montrachet.criots-batard-montrachet', 'Criots-Bâtard-Montrachet', 'criots-batard-montrachet',
  4, 13, 13, 'DRAFT', 86,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.chassagne-montrachet'),
  'SITE', 'france.bourgogne.cote-de-beaune.chassagne-montrachet.premier-cru', 'Chassagne-Montrachet 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 87,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.saint-aubin', 'Saint-Aubin', 'saint-aubin',
  3, 10, 10, 'DRAFT', 88,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.saint-aubin'),
  'SITE', 'france.bourgogne.cote-de-beaune.saint-aubin.premier-cru', 'Saint-Aubin 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 89,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.santenay', 'Santenay', 'santenay',
  3, 10, 10, 'DRAFT', 90,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.santenay'),
  'SITE', 'france.bourgogne.cote-de-beaune.santenay.premier-cru', 'Santenay 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 91,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune'),
  'APPELLATION', 'france.bourgogne.cote-de-beaune.maranges', 'Maranges', 'maranges',
  3, 10, 10, 'DRAFT', 92,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-beaune.maranges'),
  'SITE', 'france.bourgogne.cote-de-beaune.maranges.premier-cru', 'Maranges 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 93,
  true, 'AOC/AOP', 'premier_cru'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.cote-de-beaune%';
  if v_count <> 41 then
    raise exception 'expected 41 cote-de-beaune places, got %', v_count;
  end if;
end $$;
