-- Burgundy wave 3f-cdn-climats: Côte de Nuits places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.arvelets', 'Arvelets', 'arvelets',
  5, 14, 14, 'DRAFT', 500,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.clos-napoleon', 'Clos Napoléon', 'clos-napoleon',
  5, 14, 14, 'DRAFT', 501,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.clos-de-la-perriere', 'Clos de la Perrière', 'clos-de-la-perriere',
  5, 14, 14, 'DRAFT', 502,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.clos-du-chapitre', 'Clos du Chapitre', 'clos-du-chapitre',
  5, 14, 14, 'DRAFT', 503,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.hervelets', 'Hervelets', 'hervelets',
  5, 14, 14, 'DRAFT', 504,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru.les-meix-bas', 'Les Meix Bas', 'les-meix-bas',
  5, 14, 14, 'DRAFT', 505,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.au-closeau', 'Au Closeau', 'au-closeau',
  5, 14, 14, 'DRAFT', 506,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.aux-combottes', 'Aux Combottes', 'aux-combottes',
  5, 14, 14, 'DRAFT', 507,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.bel-air', 'Bel Air', 'bel-air',
  5, 14, 14, 'DRAFT', 508,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.champeaux', 'Champeaux', 'champeaux',
  5, 14, 14, 'DRAFT', 509,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.champonnet', 'Champonnet', 'champonnet',
  5, 14, 14, 'DRAFT', 510,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.cherbaudes', 'Cherbaudes', 'cherbaudes',
  5, 14, 14, 'DRAFT', 511,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.clos-prieur', 'Clos Prieur', 'clos-prieur',
  5, 14, 14, 'DRAFT', 512,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.clos-saint-jacques', 'Clos Saint-Jacques', 'clos-saint-jacques',
  5, 14, 14, 'DRAFT', 513,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.clos-des-varoilles', 'Clos des Varoilles', 'clos-des-varoilles',
  5, 14, 14, 'DRAFT', 514,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.clos-du-chapitre', 'Clos du Chapitre', 'clos-du-chapitre',
  5, 14, 14, 'DRAFT', 515,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.combe-au-moine', 'Combe au Moine', 'combe-au-moine',
  5, 14, 14, 'DRAFT', 516,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.craipillot', 'Craipillot', 'craipillot',
  5, 14, 14, 'DRAFT', 517,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.en-ergot', 'En Ergot', 'en-ergot',
  5, 14, 14, 'DRAFT', 518,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.estournelles-saint-jacques', 'Estournelles-Saint-Jacques', 'estournelles-saint-jacques',
  5, 14, 14, 'DRAFT', 519,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.fonteny', 'Fonteny', 'fonteny',
  5, 14, 14, 'DRAFT', 520,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.issarts', 'Issarts', 'issarts',
  5, 14, 14, 'DRAFT', 521,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.la-bossiere', 'La Bossière', 'la-bossiere',
  5, 14, 14, 'DRAFT', 522,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.la-perriere', 'La Perrière', 'la-perriere',
  5, 14, 14, 'DRAFT', 523,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.la-romanee', 'La Romanée', 'la-romanee',
  5, 14, 14, 'DRAFT', 524,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.lavaut-saint-jacques', 'Lavaut Saint-Jacques', 'lavaut-saint-jacques',
  5, 14, 14, 'DRAFT', 525,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.les-cazetiers', 'Les Cazetiers', 'les-cazetiers',
  5, 14, 14, 'DRAFT', 526,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.les-corbeaux', 'Les Corbeaux', 'les-corbeaux',
  5, 14, 14, 'DRAFT', 527,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.les-goulots', 'Les Goulots', 'les-goulots',
  5, 14, 14, 'DRAFT', 528,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.petite-chapelle', 'Petite Chapelle', 'petite-chapelle',
  5, 14, 14, 'DRAFT', 529,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.petits-cazetiers', 'Petits Cazetiers', 'petits-cazetiers',
  5, 14, 14, 'DRAFT', 530,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru.poissenot', 'Poissenot', 'poissenot',
  5, 14, 14, 'DRAFT', 531,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.aux-charmes', 'Aux Charmes', 'aux-charmes',
  5, 14, 14, 'DRAFT', 532,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.aux-cheseaux', 'Aux Cheseaux', 'aux-cheseaux',
  5, 14, 14, 'DRAFT', 533,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.clos-baulet', 'Clos Baulet', 'clos-baulet',
  5, 14, 14, 'DRAFT', 534,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.clos-sorbe', 'Clos Sorbè', 'clos-sorbe',
  5, 14, 14, 'DRAFT', 535,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.clos-des-ormes', 'Clos des Ormes', 'clos-des-ormes',
  5, 14, 14, 'DRAFT', 536,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.cote-rotie', 'Côte Rotie', 'cote-rotie',
  5, 14, 14, 'DRAFT', 537,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.la-bussiere', 'La Bussière', 'la-bussiere',
  5, 14, 14, 'DRAFT', 538,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.la-riotte', 'La Riotte', 'la-riotte',
  5, 14, 14, 'DRAFT', 539,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.le-village', 'Le Village', 'le-village',
  5, 14, 14, 'DRAFT', 540,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-blanchards', 'Les Blanchards', 'les-blanchards',
  5, 14, 14, 'DRAFT', 541,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-chaffots', 'Les Chaffots', 'les-chaffots',
  5, 14, 14, 'DRAFT', 542,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-charrieres', 'Les Charrières', 'les-charrieres',
  5, 14, 14, 'DRAFT', 543,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-chenevery', 'Les Chenevery', 'les-chenevery',
  5, 14, 14, 'DRAFT', 544,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-faconnieres', 'Les Faconnières', 'les-faconnieres',
  5, 14, 14, 'DRAFT', 545,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-genavrieres', 'Les Genavrières', 'les-genavrieres',
  5, 14, 14, 'DRAFT', 546,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-gruenchers', 'Les Gruenchers', 'les-gruenchers',
  5, 14, 14, 'DRAFT', 547,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-millandes', 'Les Millandes', 'les-millandes',
  5, 14, 14, 'DRAFT', 548,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-ruchots', 'Les Ruchots', 'les-ruchots',
  5, 14, 14, 'DRAFT', 549,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.les-sorbes', 'Les Sorbès', 'les-sorbes',
  5, 14, 14, 'DRAFT', 550,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru.monts-luisants', 'Monts Luisants', 'monts-luisants',
  5, 14, 14, 'DRAFT', 551,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.aux-beaux-bruns', 'Aux Beaux Bruns', 'aux-beaux-bruns',
  5, 14, 14, 'DRAFT', 552,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.aux-combottes', 'Aux Combottes', 'aux-combottes',
  5, 14, 14, 'DRAFT', 553,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.aux-echanges', 'Aux Echanges', 'aux-echanges',
  5, 14, 14, 'DRAFT', 554,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.derriere-la-grange', 'Derrière la Grange', 'derriere-la-grange',
  5, 14, 14, 'DRAFT', 555,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.la-combe-d-orveau', 'La Combe d''Orveau', 'la-combe-d-orveau',
  5, 14, 14, 'DRAFT', 556,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-amoureuses', 'Les Amoureuses', 'les-amoureuses',
  5, 14, 14, 'DRAFT', 557,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-baudes', 'Les Baudes', 'les-baudes',
  5, 14, 14, 'DRAFT', 558,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-borniques', 'Les Borniques', 'les-borniques',
  5, 14, 14, 'DRAFT', 559,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-carrieres', 'Les Carrières', 'les-carrieres',
  5, 14, 14, 'DRAFT', 560,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-chabiots', 'Les Chabiots', 'les-chabiots',
  5, 14, 14, 'DRAFT', 561,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-charmes', 'Les Charmes', 'les-charmes',
  5, 14, 14, 'DRAFT', 562,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-chatelots', 'Les Chatelots', 'les-chatelots',
  5, 14, 14, 'DRAFT', 563,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-combottes', 'Les Combottes', 'les-combottes',
  5, 14, 14, 'DRAFT', 564,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-cras', 'Les Cras', 'les-cras',
  5, 14, 14, 'DRAFT', 565,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-feusselottes-ou-les-feusselotes', 'Les Feusselottes ou Les Feusselotes', 'les-feusselottes-ou-les-feusselotes',
  5, 14, 14, 'DRAFT', 566,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-fuees', 'Les Fuées', 'les-fuees',
  5, 14, 14, 'DRAFT', 567,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-groseilles', 'Les Groseilles', 'les-groseilles',
  5, 14, 14, 'DRAFT', 568,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-gruenchers', 'Les Gruenchers', 'les-gruenchers',
  5, 14, 14, 'DRAFT', 569,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-hauts-doix', 'Les Hauts Doix', 'les-hauts-doix',
  5, 14, 14, 'DRAFT', 570,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-lavrottes', 'Les Lavrottes', 'les-lavrottes',
  5, 14, 14, 'DRAFT', 571,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-noirots', 'Les Noirots', 'les-noirots',
  5, 14, 14, 'DRAFT', 572,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-plantes', 'Les Plantes', 'les-plantes',
  5, 14, 14, 'DRAFT', 573,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-sentiers', 'Les Sentiers', 'les-sentiers',
  5, 14, 14, 'DRAFT', 574,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru.les-veroilles', 'Les Véroilles', 'les-veroilles',
  5, 14, 14, 'DRAFT', 575,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.vougeot.premier-cru.clos-de-la-perriere', 'Clos de la Perrière', 'clos-de-la-perriere',
  5, 14, 14, 'DRAFT', 576,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.vougeot.premier-cru.le-clos-blanc', 'Le Clos Blanc', 'le-clos-blanc',
  5, 14, 14, 'DRAFT', 577,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.vougeot.premier-cru.les-cras', 'Les Crâs', 'les-cras',
  5, 14, 14, 'DRAFT', 578,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.vougeot.premier-cru.les-petits-vougeots', 'Les Petits Vougeots', 'les-petits-vougeots',
  5, 14, 14, 'DRAFT', 579,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-argillas', 'Aux Argillas', 'aux-argillas',
  5, 14, 14, 'DRAFT', 580,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-boudots', 'Aux Boudots', 'aux-boudots',
  5, 14, 14, 'DRAFT', 581,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-bousselots', 'Aux Bousselots', 'aux-bousselots',
  5, 14, 14, 'DRAFT', 582,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-chaignots', 'Aux Chaignots', 'aux-chaignots',
  5, 14, 14, 'DRAFT', 583,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-champs-perdrix', 'Aux Champs Perdrix', 'aux-champs-perdrix',
  5, 14, 14, 'DRAFT', 584,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-cras', 'Aux Cras', 'aux-cras',
  5, 14, 14, 'DRAFT', 585,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-murgers', 'Aux Murgers', 'aux-murgers',
  5, 14, 14, 'DRAFT', 586,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-perdrix', 'Aux Perdrix', 'aux-perdrix',
  5, 14, 14, 'DRAFT', 587,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-thorey', 'Aux Thorey', 'aux-thorey',
  5, 14, 14, 'DRAFT', 588,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.aux-vignerondes', 'Aux Vignerondes', 'aux-vignerondes',
  5, 14, 14, 'DRAFT', 589,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.chaines-carteaux', 'Chaines Carteaux', 'chaines-carteaux',
  5, 14, 14, 'DRAFT', 590,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.chateau-gris', 'Château Gris', 'chateau-gris',
  5, 14, 14, 'DRAFT', 591,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-arlot', 'Clos Arlot', 'clos-arlot',
  5, 14, 14, 'DRAFT', 592,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-saint-marc', 'Clos Saint-Marc', 'clos-saint-marc',
  5, 14, 14, 'DRAFT', 593,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-de-la-marechale', 'Clos de la Maréchale', 'clos-de-la-marechale',
  5, 14, 14, 'DRAFT', 594,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-argillieres', 'Clos des Argillières', 'clos-des-argillieres',
  5, 14, 14, 'DRAFT', 595,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-corvees', 'Clos des Corvées', 'clos-des-corvees',
  5, 14, 14, 'DRAFT', 596,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-corvees-pagets', 'Clos des Corvées Pagets', 'clos-des-corvees-pagets',
  5, 14, 14, 'DRAFT', 597,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-forets-saint-georges', 'Clos des Forêts Saint-Georges', 'clos-des-forets-saint-georges',
  5, 14, 14, 'DRAFT', 598,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-grandes-vignes', 'Clos des Grandes Vignes', 'clos-des-grandes-vignes',
  5, 14, 14, 'DRAFT', 599,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.clos-des-porrets-saint-georges', 'Clos des Porrets-Saint-Georges', 'clos-des-porrets-saint-georges',
  5, 14, 14, 'DRAFT', 600,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.en-la-perriere-noblot', 'En la Perrière Noblot', 'en-la-perriere-noblot',
  5, 14, 14, 'DRAFT', 601,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.la-richemone', 'La Richemone', 'la-richemone',
  5, 14, 14, 'DRAFT', 602,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-argillieres', 'Les Argillières', 'les-argillieres',
  5, 14, 14, 'DRAFT', 603,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-cailles', 'Les Cailles', 'les-cailles',
  5, 14, 14, 'DRAFT', 604,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-chab-ufs', 'Les Chabœufs', 'les-chab-ufs',
  5, 14, 14, 'DRAFT', 605,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-crots', 'Les Crots', 'les-crots',
  5, 14, 14, 'DRAFT', 606,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-damodes', 'Les Damodes', 'les-damodes',
  5, 14, 14, 'DRAFT', 607,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-didiers', 'Les Didiers', 'les-didiers',
  5, 14, 14, 'DRAFT', 608,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-hauts-pruliers', 'Les Hauts Pruliers', 'les-hauts-pruliers',
  5, 14, 14, 'DRAFT', 609,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-perrieres', 'Les Perrières', 'les-perrieres',
  5, 14, 14, 'DRAFT', 610,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-porrets-saint-georges', 'Les Porrets-Saint-Georges', 'les-porrets-saint-georges',
  5, 14, 14, 'DRAFT', 611,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-poulettes', 'Les Poulettes', 'les-poulettes',
  5, 14, 14, 'DRAFT', 612,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-proces', 'Les Procès', 'les-proces',
  5, 14, 14, 'DRAFT', 613,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-pruliers', 'Les Pruliers', 'les-pruliers',
  5, 14, 14, 'DRAFT', 614,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-saints-georges', 'Les Saints-Georges', 'les-saints-georges',
  5, 14, 14, 'DRAFT', 615,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-terres-blanches', 'Les Terres Blanches', 'les-terres-blanches',
  5, 14, 14, 'DRAFT', 616,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-vallerots', 'Les Vallerots', 'les-vallerots',
  5, 14, 14, 'DRAFT', 617,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.les-vaucrains', 'Les Vaucrains', 'les-vaucrains',
  5, 14, 14, 'DRAFT', 618,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.ronciere', 'Roncière', 'ronciere',
  5, 14, 14, 'DRAFT', 619,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru.rue-de-chaux', 'Rue de Chaux', 'rue-de-chaux',
  5, 14, 14, 'DRAFT', 620,
  true, 'AOC/AOP', 'premier_cru'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.cote-de-nuits%';
  if v_count <> 174 then
    raise exception 'expected 174 cote-de-nuits places, got %', v_count;
  end if;
end $$;
