-- Details-panel content for the places that had none.
--
-- Generated by scripts/wine-map-sources/gen-place-profiles-migration.mjs from
-- data/wine-map/place-profiles.json. Do not hand-edit: the generator resolves every grape name and
-- canonical_key against the live catalog and refuses to emit anything if one of
-- them does not resolve. That check is the point of it. A grape name the
-- catalog does not carry does not raise on insert -- the join simply matches
-- nothing and the row vanishes, leaving a place quietly short of a variety.
--
-- 20 places: france 20.
-- 57 style rows, 79 grape rows, 1 Bereich articles,
-- 0 varieties added to the grape catalog.
--
-- Convention follows the existing region rows (germany.mosel, italy.piemonte):
-- role PRINCIPAL, permitted true, share_pct null. Planting percentages are not
-- invented -- france.champagne carries them because they are published.
--
-- NO TILE RUN. scripts/wine-map-tiles/export.mjs reads wine_places and
-- wine_place_boundaries only; grapes, styles and articles are served by
-- get_wine_place_context at request time. Nothing here changes a tile.

begin;

-- france.bordeaux.blaye-bourg
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.bordeaux.blaye-bourg';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.bordeaux.blaye-bourg';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Dominant on this bank', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.blaye-bourg' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.blaye-bourg' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.blaye-bourg' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.blaye-bourg' and g.name = 'Sauvignon Blanc';

-- france.bordeaux.libournais
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.bordeaux.libournais';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The right bank''s grape', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.libournais' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Bouchet locally; at its best in Saint-Émilion', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.libournais' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.bordeaux.libournais' and g.name = 'Cabernet Sauvignon';

-- france.champagne.montagne-de-reims
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.montagne-de-reims';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The Montagne''s grape, giving body and structure', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.montagne-de-reims' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.montagne-de-reims' and g.name = 'Pinot Meunier';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.montagne-de-reims' and g.name = 'Chardonnay';

-- france.champagne.cote-des-blancs
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.cote-des-blancs';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Almost to the exclusion of everything else — the Blanc de Blancs heartland', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.cote-des-blancs' and g.name = 'Chardonnay';

-- france.champagne.grande-vallee-de-la-marne
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.grande-vallee-de-la-marne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The valley''s workhorse, frost-tolerant and early-charming', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.grande-vallee-de-la-marne' and g.name = 'Pinot Meunier';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.grande-vallee-de-la-marne' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.grande-vallee-de-la-marne' and g.name = 'Chardonnay';

-- france.champagne.cote-de-sezanne
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.cote-de-sezanne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'A southern echo of the Côte des Blancs, riper and rounder', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.cote-de-sezanne' and g.name = 'Chardonnay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.cote-de-sezanne' and g.name = 'Pinot Noir';

-- france.champagne.cote-des-bar
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.cote-des-bar';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.champagne.cote-des-bar';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The great majority of the plantings', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.cote-des-bar' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.champagne.cote-des-bar' and g.name = 'Chardonnay';

-- france.languedoc-roussillon.languedoc
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.languedoc';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.languedoc';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.languedoc';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.languedoc';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.languedoc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Grenache';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Mourvèdre';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Carignan';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Cinsault';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Picpoul de Pinet, on the étang de Thau', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Picpoul';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'For the vins doux naturels of Frontignan, Lunel and Mireval', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.languedoc' and g.name = 'Muscat';

-- france.languedoc-roussillon.roussillon
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.roussillon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.roussillon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.roussillon';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.languedoc-roussillon.roussillon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Noir, gris and blanc — the basis of Banyuls and Maury', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Grenache';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Carignan';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Mourvèdre';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Macabeu';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Muscat de Rivesaltes', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.languedoc-roussillon.roussillon' and g.name = 'Muscat';

-- france.loire.pays-nantais
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.pays-nantais';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.pays-nantais';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.pays-nantais';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Muscadet, and nothing else of consequence', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.pays-nantais' and g.name = 'Melon de Bourgogne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Gros Plant du Pays Nantais', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.pays-nantais' and g.name = 'Folle Blanche';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Coteaux d''Ancenis and the Fiefs Vendéens', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.pays-nantais' and g.name = 'Gamay';

-- france.loire.anjou-saumur
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.anjou-saumur';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.anjou-saumur';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.anjou-saumur';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.anjou-saumur';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.anjou-saumur';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Dry at Savennières, nobly sweet at Quarts de Chaume and Bonnezeaux', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.anjou-saumur' and g.name = 'Chenin Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Saumur-Champigny and Anjou Villages', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.anjou-saumur' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The Rosé d''Anjou grape', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.anjou-saumur' and g.name = 'Grolleau';

-- france.loire.touraine-region
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.touraine-region';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.touraine-region';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.touraine-region';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.touraine-region';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 4, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.touraine-region';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Vouvray and Montlouis, dry through to moelleux', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.touraine-region' and g.name = 'Chenin Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Chinon, Bourgueil and Saint-Nicolas-de-Bourgueil', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.touraine-region' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.touraine-region' and g.name = 'Sauvignon Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Côt, in the Touraine reds', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.touraine-region' and g.name = 'Malbec';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Grown nowhere but Cour-Cheverny', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.touraine-region' and g.name = 'Romorantin';

-- france.loire.centre-loire
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.centre-loire';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.centre-loire';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.loire.centre-loire';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Sancerre, Pouilly-Fumé, Menetou-Salon, Quincy and Reuilly', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.centre-loire' and g.name = 'Sauvignon Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.centre-loire' and g.name = 'Pinot Noir';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Châteaumeillant', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.centre-loire' and g.name = 'Gamay';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Pouilly-sur-Loire, beside the Fumé', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.loire.centre-loire' and g.name = 'Chasselas';

-- france.rhone.septentrional
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.septentrional';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.septentrional';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.septentrional';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The only red grape of the northern Rhône', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.septentrional' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Condrieu and Château-Grillet', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.septentrional' and g.name = 'Viognier';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.septentrional' and g.name = 'Marsanne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.septentrional' and g.name = 'Roussanne';

-- france.rhone.meridional
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.meridional';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.meridional';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.meridional';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'FORTIFIED', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.meridional';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Grenache';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Syrah';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Mourvèdre';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Cinsault';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Clairette';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Bourboulenc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Muscat de Beaumes-de-Venise', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.meridional' and g.name = 'Muscat';

-- france.rhone.diois
insert into public.wine_place_articles (wine_place_id, description, climate, soils, key_facts, editorial_status)
select id, 'A high side-valley on the Drôme, east of the Rhône proper and shut off from it by the foothills of the Vercors, where the wine is sparkling and almost nothing else. Clairette de Die is made by the méthode ancestrale — a single fermentation slowed by cold and finished in the bottle — and tastes of Muscat grapes rather than of yeast, which sets it apart from every other sparkling wine in France.', 'Alpine rather than Mediterranean, and far cooler than the Rhône valley below, with wide day-to-night swings that hold on to the Muscat''s aromatics.', 'Limestone scree and clay-limestone, on terraces below the Vercors escarpment.', array['Clairette de Die, by the méthode ancestrale', 'Muscat-scented rather than yeast-driven', 'Crémant de Die is the drier, Clairette-based counterpart', 'Alpine, and cut off from the Rhône by the Vercors']::text[], 'PUBLISHED'
  from public.wine_places where canonical_key = 'france.rhone.diois';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.rhone.diois';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Muscat Blanc à Petits Grains — the scent of Clairette de Die', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.diois' and g.name = 'Muscat';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'The grape the appellation is named for, and the base of the Crémant', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.rhone.diois' and g.name = 'Clairette';

-- france.sud-ouest.bergeracois
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.bergeracois';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.bergeracois';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.bergeracois';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.bergeracois';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Merlot';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Cabernet Sauvignon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Cabernet Franc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Sémillon, and the basis of Monbazillac', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Semillon';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Sauvignon Blanc';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.bergeracois' and g.name = 'Muscadelle';

-- france.sud-ouest.garonne-tarn
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.garonne-tarn';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.garonne-tarn';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SPARKLING', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.garonne-tarn';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.garonne-tarn';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Côt or Auxerrois — Cahors is its home', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Malbec';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Fronton, and almost nowhere else', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Négrette';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Braucol at Gaillac, Mansois at Marcillac', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Fer Servadou';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Gaillac', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Duras';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Gaillac, still and méthode ancestrale', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Mauzac';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Gaillac', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.garonne-tarn' and g.name = 'Len de l''El';

-- france.sud-ouest.gascogne
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.gascogne';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.gascogne';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.gascogne';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Madiran — the most tannic red grape in France', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.gascogne' and g.name = 'Tannat';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.gascogne' and g.name = 'Gros Manseng';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Pacherenc du Vic-Bilh, often moelleux', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.gascogne' and g.name = 'Petit Manseng';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Pinenc here', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.gascogne' and g.name = 'Fer Servadou';

-- france.sud-ouest.pyrenees
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'WHITE', 0, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.pyrenees';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'SWEET', 1, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.pyrenees';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'RED', 2, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.pyrenees';
insert into public.wine_place_styles (wine_place_id, style, sort_order, editorial_status)
select id, 'ROSE', 3, 'PUBLISHED' from public.wine_places where canonical_key = 'france.sud-ouest.pyrenees';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Jurançon moelleux, picked late and shrivelled on the vine', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.pyrenees' and g.name = 'Petit Manseng';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Jurançon sec', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.pyrenees' and g.name = 'Gros Manseng';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, 'Irouléguy and Béarn', 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.pyrenees' and g.name = 'Tannat';
insert into public.wine_place_grapes (wine_place_id, grape_id, role, permitted, share_pct, local_note, editorial_status)
select p.id, g.id, 'PRINCIPAL', true, null, null, 'PUBLISHED'
  from public.wine_places p, public.grapes g
 where p.canonical_key = 'france.sud-ouest.pyrenees' and g.name = 'Cabernet Franc';

do $$
declare r record; n int;
begin
  -- Every row the data asked for is present. A grape name that failed to
  -- resolve would show up here as a short count rather than as silence.
  for r in
    select * from (values
    ('france.bordeaux.blaye-bourg', 2, 4, 1),
    ('france.bordeaux.libournais', 1, 3, 1),
    ('france.champagne.montagne-de-reims', 1, 3, 1),
    ('france.champagne.cote-des-blancs', 1, 1, 1),
    ('france.champagne.grande-vallee-de-la-marne', 1, 3, 1),
    ('france.champagne.cote-de-sezanne', 1, 2, 1),
    ('france.champagne.cote-des-bar', 2, 2, 1),
    ('france.languedoc-roussillon.languedoc', 5, 7, 1),
    ('france.languedoc-roussillon.roussillon', 4, 6, 1),
    ('france.loire.pays-nantais', 3, 3, 1),
    ('france.loire.anjou-saumur', 5, 3, 1),
    ('france.loire.touraine-region', 5, 5, 1),
    ('france.loire.centre-loire', 3, 4, 1),
    ('france.rhone.septentrional', 3, 4, 1),
    ('france.rhone.meridional', 4, 7, 1),
    ('france.rhone.diois', 1, 2, 1),
    ('france.sud-ouest.bergeracois', 4, 6, 1),
    ('france.sud-ouest.garonne-tarn', 4, 6, 1),
    ('france.sud-ouest.gascogne', 3, 4, 1),
    ('france.sud-ouest.pyrenees', 4, 4, 1)
    ) as t(key, want_styles, want_grapes, want_article)
  loop
    select count(*) into n from public.wine_place_styles s
      join public.wine_places p on p.id = s.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_styles then
      raise exception '%: % style rows, expected %', r.key, n, r.want_styles;
    end if;
    select count(*) into n from public.wine_place_grapes g
      join public.wine_places p on p.id = g.wine_place_id where p.canonical_key = r.key;
    if n <> r.want_grapes then
      raise exception '%: % grape rows, expected % — a grape name did not resolve', r.key, n, r.want_grapes;
    end if;
    select count(*) into n from public.wine_place_articles a
      join public.wine_places p on p.id = a.wine_place_id where p.canonical_key = r.key;
    if n < r.want_article then
      raise exception '%: no article', r.key;
    end if;
  end loop;

  -- No region or subregion in france, germany, italy, portugal, spain is left without wine styles.
  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION')
     and (p.canonical_key like 'france.%' or p.canonical_key like 'germany.%' or p.canonical_key like 'italy.%' or p.canonical_key like 'portugal.%' or p.canonical_key like 'spain.%')
     and not exists (select 1 from public.wine_place_styles s where s.wine_place_id = p.id);
  if n <> 0 then raise exception '% places still have no wine styles', n; end if;

  -- ...or without an article.
  select count(*) into n from public.wine_places p
   where p.kind in ('REGION','SUBREGION')
     and (p.canonical_key like 'france.%' or p.canonical_key like 'germany.%' or p.canonical_key like 'italy.%' or p.canonical_key like 'portugal.%' or p.canonical_key like 'spain.%')
     and not exists (select 1 from public.wine_place_articles a where a.wine_place_id = p.id);
  if n <> 0 then raise exception '% places still have no article', n; end if;
end $$;

commit;
