-- Burgundy wave 3f-chalonnaise-climats: Côte Chalonnaise places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.agneux', 'Agneux', 'agneux',
  5, 14, 14, 'DRAFT', 800,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.champs-cloux', 'Champs Cloux', 'champs-cloux',
  5, 14, 14, 'DRAFT', 801,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.chapitre', 'Chapitre', 'chapitre',
  5, 14, 14, 'DRAFT', 802,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.clos-st-jacques', 'Clos St Jacques', 'clos-st-jacques',
  5, 14, 14, 'DRAFT', 803,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.clos-du-chaigne', 'Clos du Chaigne', 'clos-du-chaigne',
  5, 14, 14, 'DRAFT', 804,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.cloux', 'Cloux', 'cloux',
  5, 14, 14, 'DRAFT', 805,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.gresigny', 'Grésigny', 'gresigny',
  5, 14, 14, 'DRAFT', 806,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.la-bressande', 'La Bressande', 'la-bressande',
  5, 14, 14, 'DRAFT', 807,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.la-fosse', 'La Fosse', 'la-fosse',
  5, 14, 14, 'DRAFT', 808,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.la-pucelle', 'La Pucelle', 'la-pucelle',
  5, 14, 14, 'DRAFT', 809,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.la-renarde', 'La Renarde', 'la-renarde',
  5, 14, 14, 'DRAFT', 810,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.le-meix-cadot', 'Le Meix Cadot', 'le-meix-cadot',
  5, 14, 14, 'DRAFT', 811,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.le-meix-caillet', 'Le Meix Caillet', 'le-meix-caillet',
  5, 14, 14, 'DRAFT', 812,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.les-pierres', 'Les Pierres', 'les-pierres',
  5, 14, 14, 'DRAFT', 813,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.margotes', 'Margotés', 'margotes',
  5, 14, 14, 'DRAFT', 814,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.marissou', 'Marissou', 'marissou',
  5, 14, 14, 'DRAFT', 815,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.molesme', 'Molesme', 'molesme',
  5, 14, 14, 'DRAFT', 816,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.montpalais', 'Montpalais', 'montpalais',
  5, 14, 14, 'DRAFT', 817,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.pillot', 'Pillot', 'pillot',
  5, 14, 14, 'DRAFT', 818,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.preaux', 'Préaux', 'preaux',
  5, 14, 14, 'DRAFT', 819,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.rabource', 'Rabourcé', 'rabource',
  5, 14, 14, 'DRAFT', 820,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.raclot', 'Raclot', 'raclot',
  5, 14, 14, 'DRAFT', 821,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.rully.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.rully.premier-cru.vauvry', 'Vauvry', 'vauvry',
  5, 14, 14, 'DRAFT', 822,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-marcilly', 'Clos Marcilly', 'clos-marcilly',
  5, 14, 14, 'DRAFT', 823,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-tonnerre', 'Clos Tonnerre', 'clos-tonnerre',
  5, 14, 14, 'DRAFT', 824,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-voyens', 'Clos Voyens', 'clos-voyens',
  5, 14, 14, 'DRAFT', 825,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-de-paradis', 'Clos de Paradis', 'clos-de-paradis',
  5, 14, 14, 'DRAFT', 826,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-des-barraults', 'Clos des Barraults', 'clos-des-barraults',
  5, 14, 14, 'DRAFT', 827,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-des-myglands', 'Clos des Myglands', 'clos-des-myglands',
  5, 14, 14, 'DRAFT', 828,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.clos-des-grands-voyens', 'Clos des grands Voyens', 'clos-des-grands-voyens',
  5, 14, 14, 'DRAFT', 829,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.grand-clos-fortoul', 'Grand Clos Fortoul', 'grand-clos-fortoul',
  5, 14, 14, 'DRAFT', 830,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.grifferes', 'Griffères', 'grifferes',
  5, 14, 14, 'DRAFT', 831,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.la-bondue', 'La Bondue', 'la-bondue',
  5, 14, 14, 'DRAFT', 832,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.la-cailloute', 'La Cailloute', 'la-cailloute',
  5, 14, 14, 'DRAFT', 833,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.la-chassiere', 'La Chassière', 'la-chassiere',
  5, 14, 14, 'DRAFT', 834,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.la-levriere', 'La Levrière', 'la-levriere',
  5, 14, 14, 'DRAFT', 835,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.la-mission', 'La Mission', 'la-mission',
  5, 14, 14, 'DRAFT', 836,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.le-clos-du-roy', 'Le Clos du Roy', 'le-clos-du-roy',
  5, 14, 14, 'DRAFT', 837,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.le-clos-l-eveque', 'Le Clos l''Evêque', 'le-clos-l-eveque',
  5, 14, 14, 'DRAFT', 838,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-byots', 'Les Byots', 'les-byots',
  5, 14, 14, 'DRAFT', 839,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-champs-martin', 'Les Champs Martin', 'les-champs-martin',
  5, 14, 14, 'DRAFT', 840,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-combins', 'Les Combins', 'les-combins',
  5, 14, 14, 'DRAFT', 841,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-croichots', 'Les Croichots', 'les-croichots',
  5, 14, 14, 'DRAFT', 842,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-crets', 'Les Crêts', 'les-crets',
  5, 14, 14, 'DRAFT', 843,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-fourneaux', 'Les Fourneaux', 'les-fourneaux',
  5, 14, 14, 'DRAFT', 844,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-montaigus', 'Les Montaigus', 'les-montaigus',
  5, 14, 14, 'DRAFT', 845,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-naugues', 'Les Naugues', 'les-naugues',
  5, 14, 14, 'DRAFT', 846,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-puillets', 'Les Puillets', 'les-puillets',
  5, 14, 14, 'DRAFT', 847,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-ruelles', 'Les Ruelles', 'les-ruelles',
  5, 14, 14, 'DRAFT', 848,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-saumonts', 'Les Saumonts', 'les-saumonts',
  5, 14, 14, 'DRAFT', 849,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-vasees', 'Les Vasées', 'les-vasees',
  5, 14, 14, 'DRAFT', 850,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.les-velley', 'Les Velley', 'les-velley',
  5, 14, 14, 'DRAFT', 851,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.mercurey.premier-cru.sazenay', 'Sazenay', 'sazenay',
  5, 14, 14, 'DRAFT', 852,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.a-vigne-rouge', 'A Vigne Rouge', 'a-vigne-rouge',
  5, 14, 14, 'DRAFT', 853,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.champ-nalot', 'Champ Nalot', 'champ-nalot',
  5, 14, 14, 'DRAFT', 854,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-charle', 'Clos Charlé', 'clos-charle',
  5, 14, 14, 'DRAFT', 855,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-jus', 'Clos Jus', 'clos-jus',
  5, 14, 14, 'DRAFT', 856,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-marceaux', 'Clos Marceaux', 'clos-marceaux',
  5, 14, 14, 'DRAFT', 857,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-marole', 'Clos Marole', 'clos-marole',
  5, 14, 14, 'DRAFT', 858,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-salomon', 'Clos Salomon', 'clos-salomon',
  5, 14, 14, 'DRAFT', 859,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-de-la-baraude', 'Clos de la Baraude', 'clos-de-la-baraude',
  5, 14, 14, 'DRAFT', 860,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-du-cellier-aux-moines', 'Clos du Cellier aux Moines', 'clos-du-cellier-aux-moines',
  5, 14, 14, 'DRAFT', 861,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-du-cras-long', 'Clos du Cras long', 'clos-du-cras-long',
  5, 14, 14, 'DRAFT', 862,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-du-vernoy', 'Clos du Vernoy', 'clos-du-vernoy',
  5, 14, 14, 'DRAFT', 863,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-saint-paul', 'Clos-Saint-Paul', 'clos-saint-paul',
  5, 14, 14, 'DRAFT', 864,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.clos-saint-pierre', 'Clos-Saint-Pierre', 'clos-saint-pierre',
  5, 14, 14, 'DRAFT', 865,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.crausot', 'Crausot', 'crausot',
  5, 14, 14, 'DRAFT', 866,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.cremillons', 'Crémillons', 'cremillons',
  5, 14, 14, 'DRAFT', 867,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.en-choue', 'En Choué', 'en-choue',
  5, 14, 14, 'DRAFT', 868,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.en-veau', 'En Veau', 'en-veau',
  5, 14, 14, 'DRAFT', 869,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.la-brulee', 'La Brûlée', 'la-brulee',
  5, 14, 14, 'DRAFT', 870,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.la-grande-berge', 'La Grande Berge', 'la-grande-berge',
  5, 14, 14, 'DRAFT', 871,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.la-matrosse', 'La Matrosse', 'la-matrosse',
  5, 14, 14, 'DRAFT', 872,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.la-petite-berge', 'La Petite Berge', 'la-petite-berge',
  5, 14, 14, 'DRAFT', 873,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.la-plante', 'La Plante', 'la-plante',
  5, 14, 14, 'DRAFT', 874,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-champ-lalot', 'Le Champ Lalot', 'le-champ-lalot',
  5, 14, 14, 'DRAFT', 875,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-medenchot', 'Le Médenchot', 'le-medenchot',
  5, 14, 14, 'DRAFT', 876,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-paradis', 'Le Paradis', 'le-paradis',
  5, 14, 14, 'DRAFT', 877,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-petit-pretan', 'Le Petit Prétan', 'le-petit-pretan',
  5, 14, 14, 'DRAFT', 878,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-pied-de-chaume', 'Le Pied de Chaume', 'le-pied-de-chaume',
  5, 14, 14, 'DRAFT', 879,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-pied-du-clou', 'Le Pied du Clou', 'le-pied-du-clou',
  5, 14, 14, 'DRAFT', 880,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.le-vigron', 'Le Vigron', 'le-vigron',
  5, 14, 14, 'DRAFT', 881,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-bois-chevaux', 'Les Bois Chevaux', 'les-bois-chevaux',
  5, 14, 14, 'DRAFT', 882,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-bois-gautiers', 'Les Bois Gautiers', 'les-bois-gautiers',
  5, 14, 14, 'DRAFT', 883,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-combes', 'Les Combes', 'les-combes',
  5, 14, 14, 'DRAFT', 884,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-galaffres', 'Les Galaffres', 'les-galaffres',
  5, 14, 14, 'DRAFT', 885,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-grandes-vignes', 'Les Grandes Vignes', 'les-grandes-vignes',
  5, 14, 14, 'DRAFT', 886,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.les-grands-pretans', 'Les Grands Prétans', 'les-grands-pretans',
  5, 14, 14, 'DRAFT', 887,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.petit-marole', 'Petit Marole', 'petit-marole',
  5, 14, 14, 'DRAFT', 888,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.givry.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.givry.premier-cru.servoisine', 'Servoisine', 'servoisine',
  5, 14, 14, 'DRAFT', 889,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.champ-toizeau', 'Champ Toizeau', 'champ-toizeau',
  5, 14, 14, 'DRAFT', 890,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.chazelle', 'Chazelle', 'chazelle',
  5, 14, 14, 'DRAFT', 891,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.cornevent', 'Cornevent', 'cornevent',
  5, 14, 14, 'DRAFT', 892,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.creux-de-beaux-champs', 'Creux de Beaux Champs', 'creux-de-beaux-champs',
  5, 14, 14, 'DRAFT', 893,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.l-epaule', 'L''Epaule', 'l-epaule',
  5, 14, 14, 'DRAFT', 894,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.la-condemine-du-vieux-chateau', 'La Condemine du Vieux Château', 'la-condemine-du-vieux-chateau',
  5, 14, 14, 'DRAFT', 895,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.la-grande-piece', 'La Grande Pièce', 'la-grande-piece',
  5, 14, 14, 'DRAFT', 896,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.la-moulliere', 'La Moullière', 'la-moulliere',
  5, 14, 14, 'DRAFT', 897,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.le-clos-chaudron', 'Le Clos Chaudron', 'le-clos-chaudron',
  5, 14, 14, 'DRAFT', 898,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.le-cloux', 'Le Cloux', 'le-cloux',
  5, 14, 14, 'DRAFT', 899,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.le-clouzot', 'Le Clouzot', 'le-clouzot',
  5, 14, 14, 'DRAFT', 900,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.le-vieux-chateau', 'Le Vieux Château', 'le-vieux-chateau',
  5, 14, 14, 'DRAFT', 901,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-bassets', 'Les Bassets', 'les-bassets',
  5, 14, 14, 'DRAFT', 902,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-beaux-champs', 'Les Beaux Champs', 'les-beaux-champs',
  5, 14, 14, 'DRAFT', 903,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-bonneveaux', 'Les Bonneveaux', 'les-bonneveaux',
  5, 14, 14, 'DRAFT', 904,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-bordes', 'Les Bordes', 'les-bordes',
  5, 14, 14, 'DRAFT', 905,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-bouchots', 'Les Bouchots', 'les-bouchots',
  5, 14, 14, 'DRAFT', 906,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-burnins', 'Les Burnins', 'les-burnins',
  5, 14, 14, 'DRAFT', 907,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-chaniots', 'Les Chaniots', 'les-chaniots',
  5, 14, 14, 'DRAFT', 908,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-chaumelottes', 'Les Chaumelottes', 'les-chaumelottes',
  5, 14, 14, 'DRAFT', 909,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-combes', 'Les Combes', 'les-combes',
  5, 14, 14, 'DRAFT', 910,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-coudrettes', 'Les Coudrettes', 'les-coudrettes',
  5, 14, 14, 'DRAFT', 911,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-coeres', 'Les Coères', 'les-coeres',
  5, 14, 14, 'DRAFT', 912,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-craboulettes', 'Les Craboulettes', 'les-craboulettes',
  5, 14, 14, 'DRAFT', 913,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-garcheres', 'Les Garchères', 'les-garcheres',
  5, 14, 14, 'DRAFT', 914,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-gouresses', 'Les Gouresses', 'les-gouresses',
  5, 14, 14, 'DRAFT', 915,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-jardins', 'Les Jardins', 'les-jardins',
  5, 14, 14, 'DRAFT', 916,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-las', 'Les Las', 'les-las',
  5, 14, 14, 'DRAFT', 917,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-macles', 'Les Macles', 'les-macles',
  5, 14, 14, 'DRAFT', 918,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-maroques', 'Les Maroques', 'les-maroques',
  5, 14, 14, 'DRAFT', 919,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-paquiers', 'Les Paquiers', 'les-paquiers',
  5, 14, 14, 'DRAFT', 920,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-perrieres', 'Les Perrières', 'les-perrieres',
  5, 14, 14, 'DRAFT', 921,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-pidances', 'Les Pidances', 'les-pidances',
  5, 14, 14, 'DRAFT', 922,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-platieres', 'Les Platières', 'les-platieres',
  5, 14, 14, 'DRAFT', 923,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-resses', 'Les Resses', 'les-resses',
  5, 14, 14, 'DRAFT', 924,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-treufferes', 'Les Treuffères', 'les-treufferes',
  5, 14, 14, 'DRAFT', 925,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-vignes-derriere', 'Les Vignes Derrière', 'les-vignes-derriere',
  5, 14, 14, 'DRAFT', 926,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-vignes-des-pres', 'Les Vignes des Prés', 'les-vignes-des-pres',
  5, 14, 14, 'DRAFT', 927,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.les-vignes-longues', 'Les Vignes longues', 'les-vignes-longues',
  5, 14, 14, 'DRAFT', 928,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.mont-laurent', 'Mont Laurent', 'mont-laurent',
  5, 14, 14, 'DRAFT', 929,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.montcuchot', 'Montcuchot', 'montcuchot',
  5, 14, 14, 'DRAFT', 930,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.montorge', 'Montorge', 'montorge',
  5, 14, 14, 'DRAFT', 931,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.saint-ytages', 'Saint-Ytages', 'saint-ytages',
  5, 14, 14, 'DRAFT', 932,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.sainte-morille', 'Sainte-Morille', 'sainte-morille',
  5, 14, 14, 'DRAFT', 933,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.sous-les-feilles', 'Sous les Feilles', 'sous-les-feilles',
  5, 14, 14, 'DRAFT', 934,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.vigne-du-soleil', 'Vigne du soleil', 'vigne-du-soleil',
  5, 14, 14, 'DRAFT', 935,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.vignes-couland', 'Vignes Couland', 'vignes-couland',
  5, 14, 14, 'DRAFT', 936,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.vignes-saint-pierre', 'Vignes Saint-Pierre', 'vignes-saint-pierre',
  5, 14, 14, 'DRAFT', 937,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-chalonnaise.montagny.premier-cru'),
  'SITE', 'france.bourgogne.cote-chalonnaise.montagny.premier-cru.vignes-sur-le-cloux', 'Vignes sur le Cloux', 'vignes-sur-le-cloux',
  5, 14, 14, 'DRAFT', 938,
  true, 'AOC/AOP', 'premier_cru'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.cote-chalonnaise%';
  if v_count <> 149 then
    raise exception 'expected 149 cote-chalonnaise places, got %', v_count;
  end if;
end $$;
