-- Burgundy wave 3f-maconnais-climats: Mâconnais places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.au-vignerais', 'Au Vignerais', 'au-vignerais',
  5, 14, 14, 'DRAFT', 900,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.aux-bouthieres', 'Aux Bouthières', 'aux-bouthieres',
  5, 14, 14, 'DRAFT', 901,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.aux-chailloux', 'Aux Chailloux', 'aux-chailloux',
  5, 14, 14, 'DRAFT', 902,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.aux-quarts', 'Aux Quarts', 'aux-quarts',
  5, 14, 14, 'DRAFT', 903,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.en-france', 'En France', 'en-france',
  5, 14, 14, 'DRAFT', 904,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.en-servy', 'En Servy', 'en-servy',
  5, 14, 14, 'DRAFT', 905,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.la-frerie', 'La Frérie', 'la-frerie',
  5, 14, 14, 'DRAFT', 906,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.la-marechaude', 'La Maréchaude', 'la-marechaude',
  5, 14, 14, 'DRAFT', 907,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.le-clos', 'Le Clos', 'le-clos',
  5, 14, 14, 'DRAFT', 908,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.le-clos-reyssier', 'Le Clos Reyssier', 'le-clos-reyssier',
  5, 14, 14, 'DRAFT', 909,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.le-clos-de-monsieur-noly', 'Le Clos de Monsieur Noly', 'le-clos-de-monsieur-noly',
  5, 14, 14, 'DRAFT', 910,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.le-clos-de-solutre', 'Le Clos de Solutré', 'le-clos-de-solutre',
  5, 14, 14, 'DRAFT', 911,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-brules', 'Les Brulés', 'les-brules',
  5, 14, 14, 'DRAFT', 912,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-chevrieres', 'Les Chevrières', 'les-chevrieres',
  5, 14, 14, 'DRAFT', 913,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-crays', 'Les Crays', 'les-crays',
  5, 14, 14, 'DRAFT', 914,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-menetrieres', 'Les Ménétrières', 'les-menetrieres',
  5, 14, 14, 'DRAFT', 915,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-perrieres', 'Les Perrières', 'les-perrieres',
  5, 14, 14, 'DRAFT', 916,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-reisses', 'Les Reisses', 'les-reisses',
  5, 14, 14, 'DRAFT', 917,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.les-vignes-blanches', 'Les Vignes Blanches', 'les-vignes-blanches',
  5, 14, 14, 'DRAFT', 918,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.pouilly', 'Pouilly', 'pouilly',
  5, 14, 14, 'DRAFT', 919,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.sur-la-roche', 'Sur la Roche', 'sur-la-roche',
  5, 14, 14, 'DRAFT', 920,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru'),
  'SITE', 'france.bourgogne.maconnais.pouilly-fuisse.premier-cru.vers-cras', 'Vers Cras', 'vers-cras',
  5, 14, 14, 'DRAFT', 921,
  true, 'AOC/AOP', 'premier_cru'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.maconnais%';
  if v_count <> 30 then
    raise exception 'expected 30 maconnais places, got %', v_count;
  end if;
end $$;
