-- Guess-ladder grape shortlist, curated fallback for regions the wine map doesn't
-- cover (owner report: "Common grapes in {region}" showed nothing for Austria and most
-- non-French regions). src/lib/grape-shortlist.ts's shortlist comes entirely from the
-- wine map catalog (wine_places + wine_place_grapes), which the map has only populated
-- for a handful of French places (Burgundy/Bordeaux) — every other scoring region
-- returns an empty shortlist, not an error, so the gap was silent.
--
-- public.region_grapes is a small curated table: which grapes a blind taster should
-- consider in a given scoring region, PRINCIPAL (the region's defining variety/ies) or
-- ACCESSORY (a secondary variety worth considering). Read-only from the client, written
-- only by migration, following producer_aliases' access shape (20260914113500): row
-- level security on, one select policy for authenticated, SELECT-only grants to anon/
-- authenticated/service_role, nothing for PUBLIC.
--
-- Curated from established wine-region knowledge (WSET-level facts: Wachau/Kamptal ->
-- Grüner Veltliner + Riesling, Burgenland -> Blaufränkisch + Zweigelt, etc.), not from
-- the Anthropic API (AGENTS.md's cost rules: no batch API loops for maintenance work;
-- this is the assistant's own in-session knowledge, and the script below only reads/
-- writes the database). Accuracy over breadth: 364 pairs across 168 of the 406 regions
-- the map doesn't cover, spanning every wine-producing country in the table; regions
-- with no clearly-established principal grape (emerging wine areas, ambiguous multi-
-- grape zones, or names too close to call without guessing) are left out on purpose,
-- per-country "None" sentinel regions and national table-wine tiers ("Vin de France")
-- always excluded. 18 grapes genuinely missing from public.grapes (Blaufränkisch,
-- Zweigelt, Torrontés, Bonarda, Saperavi, Rkatsiteli, Areni Noir, Voskehat, Hárslevelű,
-- Trollinger, Pinotage, Öküzgözü, Boğazkere, Koshu, Mavrud, Xynisteri, Mavro,
-- Agiorgitiko) are added first, matching the table's existing accented-name convention
-- (Grüner Veltliner, Müller-Thurgau, Gewürztraminer, ...).
--
-- src/lib/grape-shortlist.ts falls back to this table, for a region only, when the map
-- path yields no grapes; the map path stays first when it does have data.
--
-- No begin/commit: the applier wraps the file in one transaction.

create table public.region_grapes (
  region_id uuid not null references public.regions (id) on delete cascade,
  grape_id uuid not null references public.grapes (id) on delete cascade,
  role text not null check (role in ('PRINCIPAL', 'ACCESSORY')),
  primary key (region_id, grape_id)
);

alter table public.region_grapes enable row level security;

-- Who can read regions/grapes today (init_schema's "reference read"), and no write
-- policy — rows change only through migrations, same shape as producer_aliases.
create policy "region grapes read" on public.region_grapes
  for select to authenticated using (true);

-- The schema's default privileges hand anon, authenticated and service_role every table
-- privilege; curated rows keep SELECT only (producer_aliases' pattern).
revoke all on table public.region_grapes from public, anon, authenticated, service_role;
grant select on table public.region_grapes to anon, authenticated, service_role;

-- Grapes the curated pairs below need that public.grapes doesn't have yet. Exact common
-- spelling matching the table's existing naming style; colour set where unambiguous.
-- Idempotent: a name that already existed (it doesn't, verified against live data before
-- writing this file) would just be skipped.
insert into public.grapes (name, color) values
  ('Bonarda', 'RED'),
  ('Torrontés', 'WHITE'),
  ('Blaufränkisch', 'RED'),
  ('Zweigelt', 'RED'),
  ('Hárslevelű', 'WHITE'),
  ('Trollinger', 'RED'),
  ('Pinotage', 'RED'),
  ('Saperavi', 'RED'),
  ('Rkatsiteli', 'WHITE'),
  ('Areni Noir', 'RED'),
  ('Voskehat', 'WHITE'),
  ('Öküzgözü', 'RED'),
  ('Boğazkere', 'RED'),
  ('Koshu', 'WHITE'),
  ('Mavrud', 'RED'),
  ('Xynisteri', 'WHITE'),
  ('Mavro', 'RED'),
  ('Agiorgitiko', 'RED')
on conflict (name) do nothing;

-- The curated region -> grape pairs, matched by EXACT name on country + region + grape.
-- Fail-closed: every row here must join to exactly one country, one region and one
-- grape, or the insert silently drops it — the assert below catches that instead.
do $$
declare
  v_values_count constant int := 364;
  v_inserted_count int;
begin
  create temporary table _region_grapes_pairs (
    country_name text not null,
    region_name text not null,
    grape_name text not null,
    role text not null
  ) on commit drop;

  insert into _region_grapes_pairs (country_name, region_name, grape_name, role) values
    ('Argentina', 'Mendoza', 'Malbec', 'PRINCIPAL'),
    ('Argentina', 'Mendoza', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Argentina', 'Mendoza', 'Bonarda', 'ACCESSORY'),
    ('Argentina', 'Salta', 'Torrontés', 'PRINCIPAL'),
    ('Argentina', 'Salta', 'Malbec', 'ACCESSORY'),
    ('Argentina', 'San Juan', 'Syrah', 'PRINCIPAL'),
    ('Argentina', 'San Juan', 'Bonarda', 'ACCESSORY'),
    ('Argentina', 'San Juan', 'Malbec', 'ACCESSORY'),
    ('Argentina', 'La Rioja', 'Torrontés', 'PRINCIPAL'),
    ('Argentina', 'La Rioja', 'Malbec', 'ACCESSORY'),
    ('Argentina', 'Calchaqui Valley', 'Torrontés', 'PRINCIPAL'),
    ('Argentina', 'Calchaqui Valley', 'Malbec', 'ACCESSORY'),
    ('Armenia', 'Vayots Dzor', 'Areni Noir', 'PRINCIPAL'),
    ('Armenia', 'Vayots Dzor', 'Voskehat', 'ACCESSORY'),
    ('Australia', 'New South Wales', 'Semillon', 'PRINCIPAL'),
    ('Australia', 'New South Wales', 'Syrah', 'ACCESSORY'),
    ('Australia', 'South Australia', 'Syrah', 'PRINCIPAL'),
    ('Australia', 'South Australia', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Australia', 'South Australia', 'Riesling', 'ACCESSORY'),
    ('Australia', 'Victoria', 'Pinot Noir', 'PRINCIPAL'),
    ('Australia', 'Victoria', 'Chardonnay', 'ACCESSORY'),
    ('Australia', 'Victoria', 'Syrah', 'ACCESSORY'),
    ('Australia', 'Western Australia', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Australia', 'Western Australia', 'Chardonnay', 'ACCESSORY'),
    ('Australia', 'Tasmania', 'Pinot Noir', 'PRINCIPAL'),
    ('Australia', 'Tasmania', 'Chardonnay', 'ACCESSORY'),
    ('Australia', 'South Eastern Australia', 'Syrah', 'PRINCIPAL'),
    ('Australia', 'South Eastern Australia', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Australia', 'South Eastern Australia', 'Chardonnay', 'ACCESSORY'),
    ('Austria', 'Wachau', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Wachau', 'Riesling', 'PRINCIPAL'),
    ('Austria', 'Kamptal', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Kamptal', 'Riesling', 'ACCESSORY'),
    ('Austria', 'Kremstal', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Kremstal', 'Riesling', 'ACCESSORY'),
    ('Austria', 'Wagram', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Wagram', 'Riesling', 'ACCESSORY'),
    ('Austria', 'Burgenland', 'Blaufränkisch', 'PRINCIPAL'),
    ('Austria', 'Burgenland', 'Zweigelt', 'ACCESSORY'),
    ('Austria', 'Wien', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Wien', 'Riesling', 'ACCESSORY'),
    ('Austria', 'Niederosterreich', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Niederosterreich', 'Riesling', 'ACCESSORY'),
    ('Austria', 'Steiermark', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('Austria', 'Steiermark', 'Chardonnay', 'ACCESSORY'),
    ('Austria', 'Steirerland', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('Austria', 'Steirerland', 'Chardonnay', 'ACCESSORY'),
    ('Austria', 'Weinland', 'Grüner Veltliner', 'PRINCIPAL'),
    ('Austria', 'Weinland', 'Zweigelt', 'ACCESSORY'),
    ('Brazil', 'Campanha', 'Tannat', 'PRINCIPAL'),
    ('Brazil', 'Campanha', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Brazil', 'Serra Gaucha', 'Merlot', 'PRINCIPAL'),
    ('Brazil', 'Serra Gaucha', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Bulgaria', 'Thracian Lowlands', 'Mavrud', 'PRINCIPAL'),
    ('Bulgaria', 'Thracian Lowlands', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Canada', 'British Columbia', 'Pinot Noir', 'PRINCIPAL'),
    ('Canada', 'British Columbia', 'Merlot', 'ACCESSORY'),
    ('Canada', 'Ontario', 'Riesling', 'PRINCIPAL'),
    ('Canada', 'Ontario', 'Chardonnay', 'ACCESSORY'),
    ('Canada', 'Ontario', 'Cabernet Franc', 'ACCESSORY'),
    ('Chile', 'Aconcagua', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Chile', 'Aconcagua', 'Syrah', 'ACCESSORY'),
    ('Chile', 'Casablanca Valley', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('Chile', 'Casablanca Valley', 'Chardonnay', 'ACCESSORY'),
    ('Chile', 'Casablanca Valley', 'Pinot Noir', 'ACCESSORY'),
    ('Chile', 'Central Valley', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Chile', 'Central Valley', 'Carmenère', 'ACCESSORY'),
    ('Chile', 'Central Valley', 'Merlot', 'ACCESSORY'),
    ('Chile', 'Colchagua Valley', 'Carmenère', 'PRINCIPAL'),
    ('Chile', 'Colchagua Valley', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Chile', 'Colchagua Valley', 'Syrah', 'ACCESSORY'),
    ('Chile', 'Maipo Valley', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Chile', 'Maipo Valley', 'Carmenère', 'ACCESSORY'),
    ('China', 'Ningxia', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('China', 'Ningxia', 'Merlot', 'ACCESSORY'),
    ('China', 'Shandong', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('China', 'Shandong', 'Chardonnay', 'ACCESSORY'),
    ('Cyprus', 'Commandaria', 'Xynisteri', 'PRINCIPAL'),
    ('Cyprus', 'Commandaria', 'Mavro', 'ACCESSORY'),
    ('France', 'Armagnac', 'Trebbiano', 'PRINCIPAL'),
    ('France', 'Armagnac', 'Folle Blanche', 'ACCESSORY'),
    ('France', 'Auvergne', 'Gamay', 'PRINCIPAL'),
    ('France', 'Auvergne', 'Pinot Noir', 'ACCESSORY'),
    ('France', 'Bugey', 'Gamay', 'PRINCIPAL'),
    ('France', 'Bugey', 'Jacquère', 'ACCESSORY'),
    ('France', 'Charentais', 'Trebbiano', 'PRINCIPAL'),
    ('France', 'Charentais', 'Folle Blanche', 'ACCESSORY'),
    ('France', 'Cognac', 'Trebbiano', 'PRINCIPAL'),
    ('France', 'Cognac', 'Folle Blanche', 'ACCESSORY'),
    ('France', 'Coteaux du Lyonnais', 'Gamay', 'PRINCIPAL'),
    ('France', 'Coteaux du Lyonnais', 'Chardonnay', 'ACCESSORY'),
    ('France', 'Cotes Catalanes', 'Grenache', 'PRINCIPAL'),
    ('France', 'Cotes Catalanes', 'Carignan', 'ACCESSORY'),
    ('France', 'Gard', 'Grenache', 'PRINCIPAL'),
    ('France', 'Gard', 'Syrah', 'ACCESSORY'),
    ('France', 'Vaucluse', 'Grenache', 'PRINCIPAL'),
    ('France', 'Vaucluse', 'Syrah', 'ACCESSORY'),
    ('Georgia', 'Kakheti', 'Saperavi', 'PRINCIPAL'),
    ('Georgia', 'Kakheti', 'Rkatsiteli', 'PRINCIPAL'),
    ('Germany', 'Ahr', 'Pinot Noir', 'PRINCIPAL'),
    ('Germany', 'Ahr', 'Portugieser', 'ACCESSORY'),
    ('Germany', 'Baden', 'Pinot Noir', 'PRINCIPAL'),
    ('Germany', 'Baden', 'Pinot Blanc', 'ACCESSORY'),
    ('Germany', 'Franken', 'Silvaner', 'PRINCIPAL'),
    ('Germany', 'Franken', 'Müller-Thurgau', 'ACCESSORY'),
    ('Germany', 'Hessische Bergstrasse', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Hessische Bergstrasse', 'Pinot Gris', 'ACCESSORY'),
    ('Germany', 'Mittelrhein', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Mittelrhein', 'Müller-Thurgau', 'ACCESSORY'),
    ('Germany', 'Mosel', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Mosel', 'Müller-Thurgau', 'ACCESSORY'),
    ('Germany', 'Nahe', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Nahe', 'Silvaner', 'ACCESSORY'),
    ('Germany', 'Pfalz', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Pfalz', 'Dornfelder', 'ACCESSORY'),
    ('Germany', 'Rhein', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Rhein', 'Müller-Thurgau', 'ACCESSORY'),
    ('Germany', 'Rheingau', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Rheingau', 'Pinot Noir', 'ACCESSORY'),
    ('Germany', 'Rheinhessen', 'Riesling', 'PRINCIPAL'),
    ('Germany', 'Rheinhessen', 'Müller-Thurgau', 'ACCESSORY'),
    ('Germany', 'Saale-Unstrut', 'Müller-Thurgau', 'PRINCIPAL'),
    ('Germany', 'Saale-Unstrut', 'Silvaner', 'ACCESSORY'),
    ('Germany', 'Sachsen', 'Müller-Thurgau', 'PRINCIPAL'),
    ('Germany', 'Sachsen', 'Riesling', 'ACCESSORY'),
    ('Germany', 'Wurttemberg', 'Trollinger', 'PRINCIPAL'),
    ('Germany', 'Wurttemberg', 'Riesling', 'ACCESSORY'),
    ('Greece', 'Macedonia', 'Xinomavro', 'PRINCIPAL'),
    ('Greece', 'Macedonia', 'Merlot', 'ACCESSORY'),
    ('Greece', 'Nemea', 'Agiorgitiko', 'PRINCIPAL'),
    ('Greece', 'Nemea', 'Merlot', 'ACCESSORY'),
    ('Greece', 'Peloponnese', 'Agiorgitiko', 'PRINCIPAL'),
    ('Greece', 'Peloponnese', 'Muscat', 'ACCESSORY'),
    ('Greece', 'Santorini', 'Assyrtiko', 'PRINCIPAL'),
    ('Greece', 'Santorini', 'Muscat', 'ACCESSORY'),
    ('Hungary', 'Eger', 'Blaufränkisch', 'PRINCIPAL'),
    ('Hungary', 'Eger', 'Cabernet Franc', 'ACCESSORY'),
    ('Hungary', 'Egri', 'Blaufränkisch', 'PRINCIPAL'),
    ('Hungary', 'Egri', 'Cabernet Franc', 'ACCESSORY'),
    ('Hungary', 'Nagy Somlo', 'Furmint', 'PRINCIPAL'),
    ('Hungary', 'Nagy Somlo', 'Hárslevelű', 'ACCESSORY'),
    ('Hungary', 'Sopron', 'Blaufränkisch', 'PRINCIPAL'),
    ('Hungary', 'Sopron', 'Cabernet Franc', 'ACCESSORY'),
    ('Hungary', 'Szekszard', 'Blaufränkisch', 'PRINCIPAL'),
    ('Hungary', 'Szekszard', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Hungary', 'Tokaj', 'Furmint', 'PRINCIPAL'),
    ('Hungary', 'Tokaj', 'Hárslevelű', 'ACCESSORY'),
    ('Hungary', 'Villany', 'Cabernet Franc', 'PRINCIPAL'),
    ('Hungary', 'Villany', 'Blaufränkisch', 'ACCESSORY'),
    ('India', 'Maharashtra', 'Chenin Blanc', 'PRINCIPAL'),
    ('India', 'Maharashtra', 'Sauvignon Blanc', 'ACCESSORY'),
    ('India', 'Maharashtra', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Israel', 'Galilee', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Israel', 'Galilee', 'Syrah', 'ACCESSORY'),
    ('Israel', 'Judean Hills', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Israel', 'Judean Hills', 'Chardonnay', 'ACCESSORY'),
    ('Italy', 'Abruzzo', 'Montepulciano', 'PRINCIPAL'),
    ('Italy', 'Abruzzo', 'Trebbiano', 'ACCESSORY'),
    ('Italy', 'Basilicata', 'Aglianico', 'PRINCIPAL'),
    ('Italy', 'Basilicata', 'Moscato', 'ACCESSORY'),
    ('Italy', 'Calabria', 'Gaglioppo', 'PRINCIPAL'),
    ('Italy', 'Calabria', 'Greco', 'ACCESSORY'),
    ('Italy', 'Campania', 'Aglianico', 'PRINCIPAL'),
    ('Italy', 'Campania', 'Falanghina', 'ACCESSORY'),
    ('Italy', 'Campania', 'Fiano', 'ACCESSORY'),
    ('Italy', 'Emilia Romagna', 'Sangiovese', 'PRINCIPAL'),
    ('Italy', 'Emilia Romagna', 'Lambrusco di Sorbara', 'ACCESSORY'),
    ('Italy', 'Friuli', 'Friulano', 'PRINCIPAL'),
    ('Italy', 'Friuli', 'Ribolla Gialla', 'ACCESSORY'),
    ('Italy', 'Friuli Venezia Giulia', 'Friulano', 'PRINCIPAL'),
    ('Italy', 'Friuli Venezia Giulia', 'Ribolla Gialla', 'ACCESSORY'),
    ('Italy', 'Liguria', 'Vermentino', 'PRINCIPAL'),
    ('Italy', 'Liguria', 'Pigato', 'ACCESSORY'),
    ('Italy', 'Lombardia', 'Nebbiolo', 'PRINCIPAL'),
    ('Italy', 'Lombardia', 'Pinot Nero', 'ACCESSORY'),
    ('Italy', 'Marche', 'Verdicchio', 'PRINCIPAL'),
    ('Italy', 'Marche', 'Sangiovese', 'ACCESSORY'),
    ('Italy', 'Molise', 'Montepulciano', 'PRINCIPAL'),
    ('Italy', 'Molise', 'Trebbiano', 'ACCESSORY'),
    ('Italy', 'Orvieto', 'Grechetto', 'PRINCIPAL'),
    ('Italy', 'Orvieto', 'Trebbiano', 'ACCESSORY'),
    ('Italy', 'Piemonte', 'Nebbiolo', 'PRINCIPAL'),
    ('Italy', 'Piemonte', 'Barbera', 'ACCESSORY'),
    ('Italy', 'Piemonte', 'Dolcetto', 'ACCESSORY'),
    ('Italy', 'Puglia', 'Primitivo', 'PRINCIPAL'),
    ('Italy', 'Puglia', 'Negroamaro', 'ACCESSORY'),
    ('Italy', 'Sardinia', 'Cannonau', 'PRINCIPAL'),
    ('Italy', 'Sardinia', 'Vermentino', 'ACCESSORY'),
    ('Italy', 'Sicilia', 'Nero d''Avola', 'PRINCIPAL'),
    ('Italy', 'Sicilia', 'Grillo', 'ACCESSORY'),
    ('Italy', 'Toscana', 'Sangiovese', 'PRINCIPAL'),
    ('Italy', 'Toscana', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Italy', 'Toscana', 'Merlot', 'ACCESSORY'),
    ('Italy', 'Trentino Alto Adige', 'Pinot Grigio', 'PRINCIPAL'),
    ('Italy', 'Trentino Alto Adige', 'Schiava', 'ACCESSORY'),
    ('Italy', 'Trentino Alto Adige', 'Gewürztraminer', 'ACCESSORY'),
    ('Italy', 'Umbria', 'Sagrantino', 'PRINCIPAL'),
    ('Italy', 'Umbria', 'Grechetto', 'ACCESSORY'),
    ('Italy', 'Veneto', 'Corvina', 'PRINCIPAL'),
    ('Italy', 'Veneto', 'Garganega', 'ACCESSORY'),
    ('Italy', 'Veneto', 'Glera', 'ACCESSORY'),
    ('Japan', 'Hokkaido', 'Kerner', 'PRINCIPAL'),
    ('Japan', 'Hokkaido', 'Pinot Noir', 'ACCESSORY'),
    ('Japan', 'Nagano', 'Merlot', 'PRINCIPAL'),
    ('Japan', 'Nagano', 'Chardonnay', 'ACCESSORY'),
    ('Japan', 'Yamanashi', 'Koshu', 'PRINCIPAL'),
    ('Japan', 'Yamanashi', 'Merlot', 'ACCESSORY'),
    ('Lebanon', 'Bekaa Valley', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Lebanon', 'Bekaa Valley', 'Cinsault', 'ACCESSORY'),
    ('Lebanon', 'Bekaa Valley', 'Syrah', 'ACCESSORY'),
    ('Luxembourg', 'Moselle Luxembourgeoise', 'Riesling', 'PRINCIPAL'),
    ('Luxembourg', 'Moselle Luxembourgeoise', 'Pinot Gris', 'ACCESSORY'),
    ('Mexico', 'Baja California', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Mexico', 'Baja California', 'Tempranillo', 'ACCESSORY'),
    ('Mexico', 'Parras Valley', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('Mexico', 'Parras Valley', 'Malbec', 'ACCESSORY'),
    ('Morocco', 'Guerrouane', 'Cinsault', 'PRINCIPAL'),
    ('Morocco', 'Guerrouane', 'Carignan', 'ACCESSORY'),
    ('New Zealand', 'Auckland', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('New Zealand', 'Auckland', 'Chardonnay', 'ACCESSORY'),
    ('New Zealand', 'Central Otago', 'Pinot Noir', 'PRINCIPAL'),
    ('New Zealand', 'Central Otago', 'Riesling', 'ACCESSORY'),
    ('New Zealand', 'Gisborne', 'Chardonnay', 'PRINCIPAL'),
    ('New Zealand', 'Gisborne', 'Gewürztraminer', 'ACCESSORY'),
    ('New Zealand', 'Hawke''s Bay', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('New Zealand', 'Hawke''s Bay', 'Merlot', 'ACCESSORY'),
    ('New Zealand', 'Hawke''s Bay', 'Syrah', 'ACCESSORY'),
    ('New Zealand', 'Marlborough', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('New Zealand', 'Marlborough', 'Pinot Noir', 'ACCESSORY'),
    ('New Zealand', 'Nelson', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('New Zealand', 'Nelson', 'Pinot Noir', 'ACCESSORY'),
    ('New Zealand', 'Wairarapa', 'Pinot Noir', 'PRINCIPAL'),
    ('New Zealand', 'Wairarapa', 'Sauvignon Blanc', 'ACCESSORY'),
    ('Portugal', 'Acores', 'Verdelho', 'PRINCIPAL'),
    ('Portugal', 'Acores', 'Arinto', 'ACCESSORY'),
    ('Portugal', 'Alentejano', 'Trincadeira', 'PRINCIPAL'),
    ('Portugal', 'Alentejano', 'Tempranillo', 'ACCESSORY'),
    ('Portugal', 'Beiras', 'Baga', 'PRINCIPAL'),
    ('Portugal', 'Beiras', 'Touriga Nacional', 'ACCESSORY'),
    ('Portugal', 'Bucelas', 'Arinto', 'PRINCIPAL'),
    ('Portugal', 'Bucelas', 'Sercial', 'ACCESSORY'),
    ('Portugal', 'Duriense', 'Touriga Nacional', 'PRINCIPAL'),
    ('Portugal', 'Duriense', 'Touriga Franca', 'ACCESSORY'),
    ('Portugal', 'Lisboa', 'Arinto', 'PRINCIPAL'),
    ('Portugal', 'Lisboa', 'Fernão Pires', 'ACCESSORY'),
    ('Portugal', 'Madeirense', 'Tinta Negra', 'PRINCIPAL'),
    ('Portugal', 'Madeirense', 'Sercial', 'ACCESSORY'),
    ('Portugal', 'Madeirense', 'Verdelho', 'ACCESSORY'),
    ('Portugal', 'Madeirense', 'Malvasia', 'ACCESSORY'),
    ('Portugal', 'Madeirense', 'Boal', 'ACCESSORY'),
    ('Portugal', 'Moscatel de Setubal', 'Moscatel', 'PRINCIPAL'),
    ('Portugal', 'Moscatel de Setubal', 'Castelão', 'ACCESSORY'),
    ('Portugal', 'Palmela', 'Castelão', 'PRINCIPAL'),
    ('Portugal', 'Palmela', 'Moscatel', 'ACCESSORY'),
    ('Portugal', 'Pico', 'Verdelho', 'PRINCIPAL'),
    ('Portugal', 'Pico', 'Arinto', 'ACCESSORY'),
    ('Portugal', 'Port', 'Touriga Nacional', 'PRINCIPAL'),
    ('Portugal', 'Port', 'Touriga Franca', 'ACCESSORY'),
    ('Portugal', 'Porto', 'Touriga Nacional', 'PRINCIPAL'),
    ('Portugal', 'Porto', 'Touriga Franca', 'ACCESSORY'),
    ('Portugal', 'Setubal', 'Moscatel', 'PRINCIPAL'),
    ('Portugal', 'Setubal', 'Castelão', 'ACCESSORY'),
    ('Portugal', 'Tejo', 'Fernão Pires', 'PRINCIPAL'),
    ('Portugal', 'Tejo', 'Castelão', 'ACCESSORY'),
    ('Portugal', 'Terras do Dao', 'Touriga Nacional', 'PRINCIPAL'),
    ('Portugal', 'Terras do Dao', 'Encruzado', 'ACCESSORY'),
    ('Portugal', 'Tras-os-Montes', 'Touriga Nacional', 'PRINCIPAL'),
    ('Portugal', 'Tras-os-Montes', 'Touriga Franca', 'ACCESSORY'),
    ('Portugal', 'Vinho Verde', 'Alvarinho', 'PRINCIPAL'),
    ('Portugal', 'Vinho Verde', 'Loureiro', 'ACCESSORY'),
    ('Slovenia', 'Podravje', 'Sauvignon Blanc', 'PRINCIPAL'),
    ('Slovenia', 'Podravje', 'Furmint', 'ACCESSORY'),
    ('Slovenia', 'Primorska', 'Ribolla Gialla', 'PRINCIPAL'),
    ('Slovenia', 'Primorska', 'Malvasia', 'ACCESSORY'),
    ('Slovenia', 'Vipavska Dolina', 'Ribolla Gialla', 'PRINCIPAL'),
    ('Slovenia', 'Vipavska Dolina', 'Malvasia', 'ACCESSORY'),
    ('South Africa', 'Coastal Region', 'Chenin Blanc', 'PRINCIPAL'),
    ('South Africa', 'Coastal Region', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('South Africa', 'Coastal Region', 'Pinotage', 'ACCESSORY'),
    ('South Africa', 'Stellenbosch', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('South Africa', 'Stellenbosch', 'Pinotage', 'ACCESSORY'),
    ('South Africa', 'Stellenbosch', 'Chenin Blanc', 'ACCESSORY'),
    ('South Africa', 'Western Cape', 'Chenin Blanc', 'PRINCIPAL'),
    ('South Africa', 'Western Cape', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('South Africa', 'Western Cape', 'Pinotage', 'ACCESSORY'),
    ('Spain', 'Andalucia', 'Palomino', 'PRINCIPAL'),
    ('Spain', 'Andalucia', 'Pedro Ximénez', 'ACCESSORY'),
    ('Spain', 'Aragon', 'Garnacha', 'PRINCIPAL'),
    ('Spain', 'Aragon', 'Cariñena', 'ACCESSORY'),
    ('Spain', 'Castilla La Mancha', 'Tempranillo', 'PRINCIPAL'),
    ('Spain', 'Castilla La Mancha', 'Airén', 'ACCESSORY'),
    ('Spain', 'Castilla y Leon', 'Tempranillo', 'PRINCIPAL'),
    ('Spain', 'Castilla y Leon', 'Verdejo', 'ACCESSORY'),
    ('Spain', 'Catalonia', 'Garnacha', 'PRINCIPAL'),
    ('Spain', 'Catalonia', 'Cariñena', 'ACCESSORY'),
    ('Spain', 'Cava', 'Macabeu', 'PRINCIPAL'),
    ('Spain', 'Cava', 'Xarel·lo', 'ACCESSORY'),
    ('Spain', 'Cava', 'Parellada', 'ACCESSORY'),
    ('Spain', 'Galicia', 'Albariño', 'PRINCIPAL'),
    ('Spain', 'Galicia', 'Mencía', 'ACCESSORY'),
    ('Spain', 'Jerez', 'Palomino', 'PRINCIPAL'),
    ('Spain', 'Jerez', 'Pedro Ximénez', 'ACCESSORY'),
    ('Spain', 'Jumilla', 'Monastrell', 'PRINCIPAL'),
    ('Spain', 'Jumilla', 'Garnacha', 'ACCESSORY'),
    ('Spain', 'Madrid', 'Garnacha', 'PRINCIPAL'),
    ('Spain', 'Madrid', 'Tempranillo', 'ACCESSORY'),
    ('Spain', 'Murcia', 'Monastrell', 'PRINCIPAL'),
    ('Spain', 'Murcia', 'Garnacha', 'ACCESSORY'),
    ('Spain', 'Navarra', 'Garnacha', 'PRINCIPAL'),
    ('Spain', 'Navarra', 'Tempranillo', 'ACCESSORY'),
    ('Spain', 'Pais Vasco', 'Hondarrabi Zuri', 'PRINCIPAL'),
    ('Spain', 'Pais Vasco', 'Hondarrabi Beltza', 'ACCESSORY'),
    ('Spain', 'Priorat', 'Garnacha', 'PRINCIPAL'),
    ('Spain', 'Priorat', 'Cariñena', 'ACCESSORY'),
    ('Spain', 'Rías Baixas', 'Albariño', 'PRINCIPAL'),
    ('Spain', 'Rías Baixas', 'Treixadura', 'ACCESSORY'),
    ('Spain', 'Ribera del Duero', 'Tempranillo', 'PRINCIPAL'),
    ('Spain', 'Ribera del Duero', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Spain', 'Rioja', 'Tempranillo', 'PRINCIPAL'),
    ('Spain', 'Rioja', 'Garnacha', 'ACCESSORY'),
    ('Spain', 'Valencia', 'Bobal', 'PRINCIPAL'),
    ('Spain', 'Valencia', 'Monastrell', 'ACCESSORY'),
    ('Switzerland', 'Geneve', 'Chasselas', 'PRINCIPAL'),
    ('Switzerland', 'Geneve', 'Gamay', 'ACCESSORY'),
    ('Switzerland', 'Neuchatel', 'Chasselas', 'PRINCIPAL'),
    ('Switzerland', 'Neuchatel', 'Pinot Noir', 'ACCESSORY'),
    ('Switzerland', 'Svizzera Italiana', 'Merlot', 'PRINCIPAL'),
    ('Switzerland', 'Svizzera Italiana', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Switzerland', 'Ticino', 'Merlot', 'PRINCIPAL'),
    ('Switzerland', 'Ticino', 'Cabernet Sauvignon', 'ACCESSORY'),
    ('Switzerland', 'Valais', 'Chasselas', 'PRINCIPAL'),
    ('Switzerland', 'Valais', 'Pinot Noir', 'ACCESSORY'),
    ('Switzerland', 'Vaud', 'Chasselas', 'PRINCIPAL'),
    ('Switzerland', 'Vaud', 'Pinot Noir', 'ACCESSORY'),
    ('Tunisia', 'Mornag', 'Carignan', 'PRINCIPAL'),
    ('Tunisia', 'Mornag', 'Grenache', 'ACCESSORY'),
    ('Turkey', 'Eastern Anatolia', 'Öküzgözü', 'PRINCIPAL'),
    ('Turkey', 'Eastern Anatolia', 'Boğazkere', 'ACCESSORY'),
    ('United Kingdom', 'England', 'Chardonnay', 'PRINCIPAL'),
    ('United Kingdom', 'England', 'Pinot Noir', 'ACCESSORY'),
    ('United Kingdom', 'England', 'Pinot Meunier', 'ACCESSORY'),
    ('United States', 'California', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('United States', 'California', 'Chardonnay', 'ACCESSORY'),
    ('United States', 'California', 'Zinfandel', 'ACCESSORY'),
    ('United States', 'Michigan', 'Riesling', 'PRINCIPAL'),
    ('United States', 'Michigan', 'Pinot Gris', 'ACCESSORY'),
    ('United States', 'New York', 'Riesling', 'PRINCIPAL'),
    ('United States', 'New York', 'Cabernet Franc', 'ACCESSORY'),
    ('United States', 'Oregon', 'Pinot Noir', 'PRINCIPAL'),
    ('United States', 'Oregon', 'Pinot Gris', 'ACCESSORY'),
    ('United States', 'Texas', 'Tempranillo', 'PRINCIPAL'),
    ('United States', 'Texas', 'Viognier', 'ACCESSORY'),
    ('United States', 'Virginia', 'Cabernet Franc', 'PRINCIPAL'),
    ('United States', 'Virginia', 'Viognier', 'ACCESSORY'),
    ('United States', 'Walla Walla Valley', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('United States', 'Walla Walla Valley', 'Syrah', 'ACCESSORY'),
    ('United States', 'Walla Walla Valley', 'Merlot', 'ACCESSORY'),
    ('United States', 'Washington', 'Cabernet Sauvignon', 'PRINCIPAL'),
    ('United States', 'Washington', 'Merlot', 'ACCESSORY'),
    ('United States', 'Washington', 'Syrah', 'ACCESSORY'),
    ('Uruguay', 'Metropolitan', 'Tannat', 'PRINCIPAL'),
    ('Uruguay', 'Metropolitan', 'Merlot', 'ACCESSORY'),
    ('Uruguay', 'Oceanic', 'Tannat', 'PRINCIPAL'),
    ('Uruguay', 'Oceanic', 'Albariño', 'ACCESSORY');

  if (select count(*) from _region_grapes_pairs) <> v_values_count then
    raise exception '20260914131500: staged % pairs, expected % (duplicate VALUES row?)',
      (select count(*) from _region_grapes_pairs), v_values_count;
  end if;

  insert into public.region_grapes (region_id, grape_id, role)
  select r.id, g.id, p.role
  from _region_grapes_pairs p
  join public.countries c on c.name = p.country_name
  join public.regions r on r.country_id = c.id and r.name = p.region_name
  join public.grapes g on g.name = p.grape_name
  on conflict (region_id, grape_id) do nothing;

  get diagnostics v_inserted_count = row_count;

  if v_inserted_count <> v_values_count then
    raise exception '20260914131500: inserted % of % curated region_grapes pairs — % did not match a country+region+grape by exact name (or were already present)',
      v_inserted_count, v_values_count, v_values_count - v_inserted_count;
  end if;
end $$;
