-- An answer key may have no producer.
--
-- A host can genuinely not know who made a wine -- that is the whole premise of
-- an "unidentified" glass. `toUnidentifiedWine` (src/lib/wine-identity/complete.ts)
-- requires vintage, country, region and grape, NOT producer, and
-- `prepareUnidentifiedWine` passes null straight through. Live, that insert hit
-- wine_answers.producer_id NOT NULL and the add failed with a raw 23502.
-- database.types.ts has declared the column `string | null` all along, so
-- TypeScript could not catch it.
--
-- The column that would have fixed this was written on 2026-08-07 and never ran:
-- 20260807090000_optional_producer_vintage.sql collided with
-- 20260807090000_cote_de_nuits_villages.sql, and apply-migration.mjs records
-- `on conflict (version) do nothing`, so the second file left no trace either way.
-- That file is NOT reused here: its reveal_wine body predates the CLOSED
-- refusal, the null-safe host test and the locked-guess gate, so applying it
-- would revert 20260912092000. These bodies are the live ones with one case
-- changed, generated by .tiles-build/gen-140000.mjs.
--
-- Scope: producer only. The 2026-08 file also made vintage_kind nullable, but no
-- code path can produce a null vintage today (both toCompleteWine and
-- toUnidentifiedWine require it), so that half is left alone rather than shipped
-- untested. The vintage_shape CHECK is untouched for the same reason.
--
-- Scoring follows the rule the appellation, secondary grape and type designation
-- cases already use: an unknown answer scores the category NULL, never 0, so it
-- drops out of totals and out of the reveal and results rows -- scoredRows in
-- play-experience.tsx and the results page both skip a null-points row already,
-- which is why no client change rides along.
--
-- No begin/commit: the applier owns the transaction.

-- Keyed on oid, not on regprocedure::text: that text form drops the schema
-- whenever it is on search_path, so a signature match would depend on the
-- session's search_path, which this file never sets.
create temp table producer_140000_before as
select p.oid as fn, p.oid::regprocedure::text as sig, p.prosrc,
       p.proacl::text as acl, p.proconfig::text as config,
       p.prosecdef, p.proowner
from pg_proc p
where p.oid in (
  to_regprocedure('public.reveal_wine(uuid)'),
  to_regprocedure('public.score_own_guess(uuid)'),
  to_regprocedure('public.in_play_steps(uuid)')
);

-- Refuse unless every live body is the one this file was generated from.
do $$
declare
  v_want jsonb := '{"public.reveal_wine(uuid)":"13923813da0f470fe2d1ffd3ac445625","public.score_own_guess(uuid)":"f7acab278d1a88558b1e35b4370e72e4","public.in_play_steps(uuid)":"09f3924f8aae6df2ce846eb85b025f0c"}'::jsonb;
  v_sig text;
  v_got text;
begin
  if (select count(*) from producer_140000_before) <> 3 then
    raise exception 'expected all three functions pre-migration, found %',
      (select count(*) from producer_140000_before);
  end if;
  for v_sig in select jsonb_object_keys(v_want) loop
    select md5(replace(prosrc, chr(13), '')) into v_got
    from producer_140000_before where fn = to_regprocedure(v_sig);
    if v_got is null then
      raise exception '% missing pre-migration', v_sig;
    end if;
    if v_got <> (v_want ->> v_sig) then
      raise exception '% live body differs from the one this migration was generated from; rerun gen-140000.mjs', v_sig;
    end if;
  end loop;
end $$;

-- 1. The column itself.
alter table public.wine_answers alter column producer_id drop not null;

-- 2. 'producer' becomes a conditional step, as 'appellation' already is. This is
--    what keeps reveal_next_category right without editing it: a step absent
--    from the array never runs its scoring branch, so producer_points keeps the
--    column default of NULL.
CREATE OR REPLACE FUNCTION public.in_play_steps(p_wine_id uuid)
 RETURNS text[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select array_remove(array[
    'country', 'region',
    case when a.appellation_id is not null then 'appellation' end,
    'grapes',
    case when a.producer_id is not null then 'producer' end,
    case when a.type_designation_id is not null then 'type_designation' end,
    'vintage'
  ], null)
  from wine_answers a where a.wine_id = p_wine_id;
$function$
;

-- 3. The two functions that score every category in one statement.
CREATE OR REPLACE FUNCTION public.reveal_wine(p_wine_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_answer wine_answers%rowtype;
  v_tasting_id uuid;
  v_contributor_participant_id uuid;
  v_is_host boolean;
  v_is_participant boolean;
  v_eligible_count int;
  v_guess_count int;
  v_reveal_mode reveal_mode_type;
  v_status tasting_status;
  v_wine_source wine_source_mode;
  v_host_id uuid;
begin
  select w.tasting_id, w.contributor_participant_id, t.host_id = auth.uid(), t.reveal_mode,
         t.status, t.wine_source, t.host_id
    into v_tasting_id, v_contributor_participant_id, v_is_host, v_reveal_mode,
         v_status, v_wine_source, v_host_id
  from wines w
  join tastings t on t.id = w.tasting_id
  where w.id = p_wine_id;

  if v_tasting_id is null then
    raise exception 'Wine % not found', p_wine_id;
  end if;

  if v_status = 'CLOSED' then
    raise exception 'Tasting is finished';
  end if;

  if not coalesce(v_is_host, false) then
    select exists (
      select 1 from tasting_participants
      where tasting_id = v_tasting_id and user_id = auth.uid()
    ) into v_is_participant;

    if not v_is_participant then
      raise exception 'Only the host or a participant can reveal a wine';
    end if;

    select count(*) into v_eligible_count
    from tasting_participants
    where tasting_id = v_tasting_id
      and status = 'JOINED'
      and id is distinct from v_contributor_participant_id
      and not (v_wine_source = 'HOST_PROVIDES' and user_id = v_host_id);

    select count(*) into v_guess_count
    from tasting_participants p
    where p.tasting_id = v_tasting_id
      and p.status = 'JOINED'
      and p.id is distinct from v_contributor_participant_id
      and not (v_wine_source = 'HOST_PROVIDES' and p.user_id = v_host_id)
      and exists (
        select 1 from guesses g
        where g.wine_id = p_wine_id
          and g.participant_id = p.id
          and g.locked_at is not null
      );

    if v_eligible_count = 0 or v_guess_count < v_eligible_count then
      raise exception 'Not everyone has guessed yet — only the host can reveal early';
    end if;
  end if;

  select * into v_answer from wine_answers where wine_id = p_wine_id;
  if not found then
    raise exception 'Wine % has no answer key recorded', p_wine_id;
  end if;

  if v_reveal_mode = 'SEMI_BLIND' then
    update guesses g
    set
      country_points = null,
      region_points = null,
      appellation_points = null,
      primary_grape_points = null,
      secondary_grape_points = null,
      producer_points = null,
      type_designation_points = null,
      vintage_points = null,
      total_points = case when g.guessed_wine_id = p_wine_id then 1 else 0 end,
      scored_at = now()
    where g.wine_id = p_wine_id;
  else
    update guesses g
    set
      country_points = case when g.country_id = v_answer.country_id then 2 else 0 end,
      region_points = case when g.region_id = v_answer.region_id then 3 else 0 end,
      appellation_points = case
        when v_answer.appellation_id is null then null
        when g.appellation_id = v_answer.appellation_id then 5
        else 0
      end,
      primary_grape_points = case when g.primary_grape_id = v_answer.primary_grape_id then 8 else 0 end,
      secondary_grape_points = case
        when v_answer.secondary_grape_id is null then null
        when g.secondary_grape_id = v_answer.secondary_grape_id then 2
        else 0
      end,
      producer_points = case
        when v_answer.producer_id is null then null
        when g.producer_id = v_answer.producer_id then 6
        else 0
      end,
      type_designation_points = case
        when v_answer.type_designation_id is null then null
        when g.type_designation_id = v_answer.type_designation_id then 2
        else 0
      end,
      vintage_points = case
        when g.vintage_kind is null then 0
        when g.vintage_kind = v_answer.vintage_kind
          and g.vintage_kind = 'NV' then 2
        when g.vintage_kind = v_answer.vintage_kind
          and g.vintage_kind = 'TAWNY'
          and g.vintage_tawny_years = v_answer.vintage_tawny_years then 2
        when g.vintage_kind = v_answer.vintage_kind
          and g.vintage_kind = 'YEAR'
          and g.vintage_year = v_answer.vintage_year then 2
        when g.vintage_kind = v_answer.vintage_kind
          and g.vintage_kind = 'YEAR'
          and abs(g.vintage_year - v_answer.vintage_year) = 1 then 1
        else 0
      end,
      scored_at = now()
    where g.wine_id = p_wine_id;

    update guesses
    set total_points = coalesce(country_points, 0)
      + coalesce(region_points, 0)
      + coalesce(appellation_points, 0)
      + coalesce(primary_grape_points, 0)
      + coalesce(secondary_grape_points, 0)
      + coalesce(producer_points, 0)
      + coalesce(type_designation_points, 0)
      + coalesce(vintage_points, 0)
    where wine_id = p_wine_id;
  end if;

  update wines set is_revealed = true where id = p_wine_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.score_own_guess(p_wine_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_answer wine_answers%rowtype;
  v_tasting_id uuid;
  v_reveal_mode reveal_mode_type;
  v_timing timing_mode;
  v_policy async_reveal_type;
  v_participant_id uuid;
begin
  select w.tasting_id, t.reveal_mode, t.timing_mode, t.async_reveal_policy
    into v_tasting_id, v_reveal_mode, v_timing, v_policy
  from wines w
  join tastings t on t.id = w.tasting_id
  where w.id = p_wine_id;

  if v_tasting_id is null then
    return;
  end if;
  if v_timing <> 'ASYNC' or v_policy <> 'IMMEDIATE' then
    return;
  end if;

  select id into v_participant_id
  from tasting_participants
  where tasting_id = v_tasting_id and user_id = auth.uid() and status = 'JOINED';
  if v_participant_id is null then
    return;
  end if;

  select * into v_answer from wine_answers where wine_id = p_wine_id;
  if not found then
    return;
  end if;

  if v_reveal_mode = 'SEMI_BLIND' then
    update guesses g
    set
      country_points = null,
      region_points = null,
      appellation_points = null,
      primary_grape_points = null,
      secondary_grape_points = null,
      producer_points = null,
      type_designation_points = null,
      vintage_points = null,
      total_points = case when g.guessed_wine_id = p_wine_id then 1 else 0 end,
      scored_at = now()
    where g.wine_id = p_wine_id
      and g.participant_id = v_participant_id
      and g.scored_at is null;
  else
    update guesses g
    set
      country_points = case when g.country_id = v_answer.country_id then 2 else 0 end,
      region_points = case when g.region_id = v_answer.region_id then 3 else 0 end,
      appellation_points = case
        when v_answer.appellation_id is null then null
        when g.appellation_id = v_answer.appellation_id then 5
        else 0
      end,
      primary_grape_points = case when g.primary_grape_id = v_answer.primary_grape_id then 8 else 0 end,
      secondary_grape_points = case
        when v_answer.secondary_grape_id is null then null
        when g.secondary_grape_id = v_answer.secondary_grape_id then 2
        else 0
      end,
      producer_points = case
        when v_answer.producer_id is null then null
        when g.producer_id = v_answer.producer_id then 6
        else 0
      end,
      type_designation_points = case
        when v_answer.type_designation_id is null then null
        when g.type_designation_id = v_answer.type_designation_id then 2
        else 0
      end,
      vintage_points = case
        when g.vintage_kind is null then 0
        when g.vintage_kind = v_answer.vintage_kind and g.vintage_kind = 'NV' then 2
        when g.vintage_kind = v_answer.vintage_kind and g.vintage_kind = 'TAWNY'
          and g.vintage_tawny_years = v_answer.vintage_tawny_years then 2
        when g.vintage_kind = v_answer.vintage_kind and g.vintage_kind = 'YEAR'
          and g.vintage_year = v_answer.vintage_year then 2
        when g.vintage_kind = v_answer.vintage_kind and g.vintage_kind = 'YEAR'
          and abs(g.vintage_year - v_answer.vintage_year) = 1 then 1
        else 0
      end,
      scored_at = now()
    where g.wine_id = p_wine_id
      and g.participant_id = v_participant_id
      and g.scored_at is null;

    update guesses
    set total_points = coalesce(country_points, 0)
      + coalesce(region_points, 0)
      + coalesce(appellation_points, 0)
      + coalesce(primary_grape_points, 0)
      + coalesce(secondary_grape_points, 0)
      + coalesce(producer_points, 0)
      + coalesce(type_designation_points, 0)
      + coalesce(vintage_points, 0)
    where wine_id = p_wine_id and participant_id = v_participant_id;
  end if;
end;
$function$
;

-- Same-transaction assertions.
do $$
declare
  v_before record;
  v_after record;
  v_guard constant text := replace($lit$      producer_points = case
        when v_answer.producer_id is null then null
        when g.producer_id = v_answer.producer_id then 6
        else 0
      end,$lit$, chr(13), '');
begin
  -- The column is nullable and nothing else about it moved.
  if (select is_nullable from information_schema.columns
       where table_schema = 'public' and table_name = 'wine_answers'
         and column_name = 'producer_id') <> 'YES' then
    raise exception 'wine_answers.producer_id is still NOT NULL post-migration';
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.wine_answers'::regclass
      and conname = 'wine_answers_producer_id_fkey') then
    raise exception 'the producer foreign key was dropped post-migration';
  end if;

  -- Security, ownership and grants are untouched on all three functions.
  for v_before in select * from producer_140000_before loop
    -- CREATE OR REPLACE keeps the oid, so this matches the same function even
    -- though its body has changed.
    select p.prosrc, p.proacl::text as acl, p.proconfig::text as config,
           p.prosecdef, p.proowner
      into v_after
    from pg_proc p where p.oid = v_before.fn;
    if not found then
      raise exception '% missing post-migration', v_before.sig;
    end if;
    if v_after.prosecdef is distinct from v_before.prosecdef
       or v_after.config is distinct from v_before.config
       or v_after.proowner is distinct from v_before.proowner
       or v_after.acl is distinct from v_before.acl then
      raise exception '% changed security, search_path, owner or grants post-migration', v_before.sig;
    end if;
  end loop;

  -- The producer guard landed in both scoring functions, exactly once each.
  for v_after in
    select p.oid::regprocedure::text as sig, replace(p.prosrc, chr(13), '') as src
    from pg_proc p
    where p.oid in (to_regprocedure('public.reveal_wine(uuid)'),
                    to_regprocedure('public.score_own_guess(uuid)'))
  loop
    if strpos(v_after.src, v_guard) = 0 then
      raise exception '% did not get the producer null guard', v_after.sig;
    end if;
    if strpos(v_after.src, 'producer_points = case when g.producer_id') > 0 then
      raise exception '% still holds the unguarded producer case', v_after.sig;
    end if;
  end loop;

  -- 20260912092000's fixes are still standing in reveal_wine: this migration
  -- exists because an older file would have reverted exactly these.
  if (select strpos(replace(prosrc, chr(13), ''), 'if not coalesce(v_is_host, false) then')
        from pg_proc where oid = to_regprocedure('public.reveal_wine(uuid)')) = 0 then
    raise exception 'reveal_wine lost its null-safe host test';
  end if;
  if (select strpos(replace(prosrc, chr(13), ''), 'and g.locked_at is not null')
        from pg_proc where oid = to_regprocedure('public.reveal_wine(uuid)')) = 0 then
    raise exception 'reveal_wine lost its locked-guess gate';
  end if;
  if (select strpos(replace(prosrc, chr(13), ''), 'Tasting is finished')
        from pg_proc where oid = to_regprocedure('public.reveal_wine(uuid)')) = 0 then
    raise exception 'reveal_wine lost its CLOSED refusal';
  end if;

  -- in_play_steps drops 'producer' exactly when the answer has none.
  if (select strpos(replace(prosrc, chr(13), ''), 'case when a.producer_id is not null then ''producer'' end')
        from pg_proc where oid = to_regprocedure('public.in_play_steps(uuid)')) = 0 then
    raise exception 'in_play_steps did not make producer conditional';
  end if;
end $$;

drop table producer_140000_before;
