-- Phase 3C wave 5b: Côte de Nuits places as DRAFT. Boundaries are
-- staged separately by build-boundary.mjs; a flip migration marks them
-- VERIFIED once the owner approves the shapes.
-- Generated by scripts/wine-map-sources/generate-cote-de-nuits.mjs.

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.marsannay', 'Marsannay', 'marsannay',
  3, 10, 10, 'DRAFT', 24,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.fixin', 'Fixin', 'fixin',
  3, 10, 10, 'DRAFT', 25,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.fixin'),
  'SITE', 'france.bourgogne.cote-de-nuits.fixin.premier-cru', 'Fixin 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 26,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin', 'Gevrey-Chambertin', 'gevrey-chambertin',
  3, 10, 10, 'DRAFT', 27,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.chambertin', 'Chambertin', 'chambertin',
  4, 13, 13, 'DRAFT', 28,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.chambertin-clos-de-beze', 'Chambertin-Clos de Bèze', 'chambertin-clos-de-beze',
  4, 13, 13, 'DRAFT', 29,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.chapelle-chambertin', 'Chapelle-Chambertin', 'chapelle-chambertin',
  4, 13, 13, 'DRAFT', 30,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.charmes-chambertin', 'Charmes-Chambertin', 'charmes-chambertin',
  4, 13, 13, 'DRAFT', 31,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.griotte-chambertin', 'Griotte-Chambertin', 'griotte-chambertin',
  4, 13, 13, 'DRAFT', 32,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.latricieres-chambertin', 'Latricières-Chambertin', 'latricieres-chambertin',
  4, 13, 13, 'DRAFT', 33,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.mazis-chambertin', 'Mazis-Chambertin', 'mazis-chambertin',
  4, 13, 13, 'DRAFT', 34,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.mazoyeres-chambertin', 'Mazoyères-Chambertin', 'mazoyeres-chambertin',
  4, 13, 13, 'DRAFT', 35,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.ruchottes-chambertin', 'Ruchottes-Chambertin', 'ruchottes-chambertin',
  4, 13, 13, 'DRAFT', 36,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.gevrey-chambertin'),
  'SITE', 'france.bourgogne.cote-de-nuits.gevrey-chambertin.premier-cru', 'Gevrey-Chambertin 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 37,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.morey-saint-denis', 'Morey-Saint-Denis', 'morey-saint-denis',
  3, 10, 10, 'DRAFT', 38,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.morey-saint-denis.clos-de-la-roche', 'Clos de la Roche', 'clos-de-la-roche',
  4, 13, 13, 'DRAFT', 39,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.morey-saint-denis.clos-saint-denis', 'Clos Saint-Denis', 'clos-saint-denis',
  4, 13, 13, 'DRAFT', 40,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.morey-saint-denis.clos-des-lambrays', 'Clos des Lambrays', 'clos-des-lambrays',
  4, 13, 13, 'DRAFT', 41,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.morey-saint-denis.clos-de-tart', 'Clos de Tart', 'clos-de-tart',
  4, 13, 13, 'DRAFT', 42,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.morey-saint-denis'),
  'SITE', 'france.bourgogne.cote-de-nuits.morey-saint-denis.premier-cru', 'Morey-Saint-Denis 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 43,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.chambolle-musigny', 'Chambolle-Musigny', 'chambolle-musigny',
  3, 10, 10, 'DRAFT', 44,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.chambolle-musigny.bonnes-mares', 'Bonnes-Mares', 'bonnes-mares',
  4, 13, 13, 'DRAFT', 45,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.chambolle-musigny.musigny', 'Musigny', 'musigny',
  4, 13, 13, 'DRAFT', 46,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.chambolle-musigny'),
  'SITE', 'france.bourgogne.cote-de-nuits.chambolle-musigny.premier-cru', 'Chambolle-Musigny 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 47,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.vougeot', 'Vougeot', 'vougeot',
  3, 10, 10, 'DRAFT', 48,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.vougeot.clos-de-vougeot', 'Clos de Vougeot', 'clos-de-vougeot',
  4, 13, 13, 'DRAFT', 49,
  true, 'AOC/AOP', 'grand_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.vougeot'),
  'SITE', 'france.bourgogne.cote-de-nuits.vougeot.premier-cru', 'Vougeot 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 50,
  true, 'AOC/AOP', 'premier_cru'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits'),
  'APPELLATION', 'france.bourgogne.cote-de-nuits.nuits-saint-georges', 'Nuits-Saint-Georges', 'nuits-saint-georges',
  3, 10, 10, 'DRAFT', 51,
  true, 'AOC/AOP', 'communal'
);

insert into wine_places (primary_parent_id, kind, canonical_key, name, slug,
  display_tier, min_zoom, label_min_zoom, publication_status, sort_order,
  is_appellation, appellation_system, appellation_level)
values (
  (select id from wine_places where canonical_key = 'france.bourgogne.cote-de-nuits.nuits-saint-georges'),
  'SITE', 'france.bourgogne.cote-de-nuits.nuits-saint-georges.premier-cru', 'Nuits-Saint-Georges 1er Cru', 'premier-cru',
  4, 12, 12, 'DRAFT', 52,
  true, 'AOC/AOP', 'premier_cru'
);

do $$
declare v_count int;
begin
  select count(*) into v_count from wine_places
   where canonical_key like 'france.bourgogne.cote-de-nuits%';
  if v_count <> 53 then
    raise exception 'expected 53 Cote de Nuits places, got %', v_count;
  end if;
end $$;
