// The admin typical-wine editor's own words (English: the admin is not
// translated). The WSET sections, their rows, Close and the section step come
// from the sheet's i18n (src/lib/wset/i18n.ts), as in the note form; the Wine
// tab and the save/discard lines keep the old editor's wording where it had one.
export const EDITOR_COPY = {
  editProfile: "Edit profile",
  eyebrow: "Typical wine",
  untitled: "Untitled typical wine",
  wineTab: "Wine",
  wineRated: "where it scores",
  name: "Name",
  colour: "Colour",
  style: "Style",
  country: "Country",
  region: "Region",
  appellation: "Appellation",
  pickCountry: "Pick a country",
  pickRegion: "Pick a region",
  pickCountryFirst: "Pick a country first",
  pickAppellation: "Just the region, or pick one",
  pickRegionFirst: "Pick a region first",
  primaryGrape: "Primary grape",
  secondGrape: "Second grape",
  pickGrape: "Pick a grape",
  noSecondGrape: "None",
  optional: "optional",
  designations: "Designations the label would carry",
  addDesignation: "Add a designation",
  removeItem: (name: string) => `Remove ${name}`,
  typicalAge: "Typical age (years)",
  typicalAgeFrom: "Typical age from (years)",
  typicalAgeTo: "Typical age to (years)",
  to: "to",
  mapPlace: "Map place (optional)",
  mapPlaceNone: "None — not on the map",
  mapPlaceSearch: "Search the map…",
  removePlace: "Remove the map place",
  description: "Description",
  signatureHint: "Signature terms — an exact hit earns a bonus",
  signatureLabel: (term: string) => `Signature term: ${term}`,
  ofTotalSet: (total: number) => `of ${total} set`,
  footerNote: "A name, where it scores and a grape are required. Every range is optional.",
  save: "Save profile",
  saving: "Saving…",
  saved: "Saved ✓",
  retry: "Retry save",
  saveFailed: "The save did not go through. Try again.",
  discardTitle: "Discard your changes?",
  discardBody: "Your changes to this typical wine haven't been saved and will be lost.",
  keepEditing: "Keep editing",
  discard: "Discard",
} as const;
